import { defineGuestCopyV2 } from './guest-copy-v2'

// English guest copy, generation 2 (schema version 3 snapshots). Wording
// follows the round 4 boards G01-G12. Industry-neutral: a guest has a visit,
// and nothing here names a kind of place.
export const enV2 = defineGuestCopyV2({
  locale: 'en',
  version: 'guest-ui-en-v2',
  copy: {
    languageChipLabel: 'Language',
    languageSheetTitle: 'Language',
    languageSheetHint: 'This page opens in your phone’s language when it has it.',
    languageSheetClose: 'Close',
    languageCurrent: 'Selected',
    privacyNoticeLink: 'Privacy notice',
    footerMadeWith: 'Made with Reputation Key',
    logoAlt: '{name} logo',
    visitNotice: 'This page counts visits for {name}. No ads or third‑party trackers.',
    visitNoticeLabel: 'Visit counting',
    visitNoticeAcknowledge: 'Got it',

    ratingTitle: 'How was your experience?',
    ratingWord1: 'Poor',
    ratingWord2: 'Fair',
    ratingWord3: 'Good',
    ratingWord4: 'Very good',
    ratingWord5: 'Excellent',
    ratingScaleLow: 'Poor',
    ratingScaleHigh: 'Excellent',
    ratingGroupLabel: 'Rating',
    ratingOption: '{stars}, {word}',
    ratingChoose: 'Choose a rating from 1 to 5 stars.',
    ratingSend: 'Send privately',
    ratingPrivacyLine: 'Shared privately with {name}.',
    ratingSaveFailed: 'Your rating could not be saved. Please try again.',
    sending: 'Sending…',
    honeypotLabel: 'Website',
    errorGeneric: 'Something went wrong. Please try again.',

    ratingThanks: 'Thank you.',
    ratingSentTitle: 'Rating sent privately',
    ratingSentSummary: '{word} · sent privately',
    ratingChange: 'Change',
    ratingUpdated: 'Your rating was updated.',

    googleTitle: 'Share your experience on Google',
    googleBody: 'If you’d like, you can also leave a public review on Google.',
    googleAction: 'Continue to Google',
    googleOpensLabel: '(opens Google)',
    googleHint: 'Opens Google · you may need to sign in',
    googleUnavailableTitle: 'Google can’t be opened from here right now',
    googleUnavailableBody: 'Your rating reached {name} privately. Thank you.',
    googleOpenFailed: 'Google could not be opened. Please try again.',

    noteOfferTitle: 'Add a private note for the team',
    noteOfferBody: 'Optional. Shared privately with {name}.',
    noteOfferAction: 'Write a private note',
    noteLabel: 'Your note (optional)',
    noteHint: 'No need to include your name.',
    noteSend: 'Send note privately',
    noteDismiss: 'Not now',
    noteRequired: 'Write your note before sending it.',
    noteSent: 'Your note was sent privately to {name}.',
    noteSendFailed: 'Your note could not be sent. Please try again.',

    responseTitle: 'Your response',
    responseSummary: 'Change, remove or start over',
    responseChangeTitle: 'Change your rating',
    responseChangeSave: 'Save new rating',
    responseRemoveNoteTitle: 'Remove your note',
    responseRemoveNoteAction: 'Remove',
    responseRemoveNoteDone: 'Your note was removed. Your rating remains saved.',
    responseRemoveNoteFailed: 'Your note could not be removed. Please try again.',
    responseRemoveAllTitle: 'Remove your rating and note',
    responseRemoveAllNote: 'Anything you posted on Google isn’t affected.',
    responseRemoveAllAction: 'Remove…',
    responseRemoveAllConfirmTitle: 'Remove your rating and note?',
    responseRemoveAllConfirmBody: 'Both will be deleted. This can’t be undone.',
    responseRemoveAllConfirm: 'Remove both',
    responseRemoveAllCancel: 'Keep them',
    responseRemoveAllDoneTitle: 'Your response was removed',
    responseRemoveAllDoneBody: 'Your rating and note were deleted.',
    responseRemoveAllFailed: 'Your response could not be removed. Please try again.',

    deadlineToday: 'Until {time} today, {zone} time',
    deadlineTomorrow: 'Until {time} tomorrow, {zone} time',
    deadlineDate: 'Until {date}, {time}, {zone} time',
    windowEndedChange: 'The time to change your rating has ended.',
    windowEndedNote: 'The time to remove your note has ended.',
    windowEndedAll: 'The time to remove your response has ended.',

    sharedDeviceTitle: 'Shared phone or tablet?',
    sharedDeviceBody: 'Start over so the next guest begins with a fresh page.',
    startOverAction: 'Start over on this device',
    startOverDone: 'Ready for the next guest. Your earlier response remains saved.',
    startOverFailed: 'Could not start over. Please try again.',

    linktreeDefaultTitle: 'Useful links',
    unavailableTitle: 'This page isn’t available right now.',
    unavailableBody: 'Please check back later.',
  },
  plurals: {
    ratingStars: { one: '{count} star', other: '{count} stars' },
  },
})
