import { defineGuestCopyV2 } from './guest-copy-v2'

// Spanish guest copy, generation 2 (schema version 3 snapshots). The form of
// address is the polite "usted" (su, inténtelo, elija), the counterpart of the
// German "Sie". No native check happens during the closed beta (owner decision
// 5, 2026-09-30). Industry-neutral: no text names a kind of place; "huésped"
// is the word for "guest" that the owner keeps in every industry.
export const esV2 = defineGuestCopyV2({
  locale: 'es',
  version: 'guest-ui-es-v2',
  copy: {
    languageChipLabel: 'Idioma',
    languageSheetTitle: 'Idioma',
    languageSheetHint:
      'Esta página se abre en el idioma de su teléfono cuando está disponible.',
    languageSheetClose: 'Cerrar',
    languageCurrent: 'Seleccionado',
    languageNameEn: 'Inglés',
    languageNameBg: 'Búlgaro',
    languageNameEs: 'Español',
    languageNameIt: 'Italiano',
    languageNameFr: 'Francés',
    languageNameDe: 'Alemán',
    privacyNoticeLink: 'Aviso de privacidad',
    footerMadeWith: 'Creado con Reputation Key',
    logoAlt: 'Logotipo de {name}',
    visitNotice:
      'Esta página cuenta las visitas de {name}. Sin publicidad ni rastreadores de terceros.',
    visitNoticeDetail:
      'Una cookie de sesión esencial protege su respuesta. Por separado, contamos esta visita para {name} con un marcador de red de corta duración que protege su privacidad. Sin publicidad ni rastreadores de terceros.',
    visitNoticeLabel: 'Recuento de visitas',
    visitNoticeAcknowledge: 'Entendido',

    ratingTitle: '¿Cómo fue su experiencia?',
    ratingWord1: 'Malo',
    ratingWord2: 'Regular',
    ratingWord3: 'Bueno',
    ratingWord4: 'Muy bueno',
    ratingWord5: 'Excelente',
    ratingScaleLow: 'Malo',
    ratingScaleHigh: 'Excelente',
    ratingGroupLabel: 'Valoración',
    ratingOption: '{stars}, {word}',
    ratingChoose: 'Elija una valoración de 1 a 5 estrellas.',
    ratingSend: 'Enviar en privado',
    ratingPrivacyLine: 'Se comparte en privado con {name}.',
    ratingSaveFailed: 'No se pudo guardar su valoración. Inténtelo de nuevo.',
    sending: 'Enviando…',
    honeypotLabel: 'Sitio web',
    errorGeneric: 'Algo salió mal. Inténtelo de nuevo.',

    ratingThanks: 'Gracias.',
    ratingSentTitle: 'Valoración enviada en privado',
    ratingSentSummary: '{word} · enviada en privado',
    ratingChange: 'Cambiar',
    ratingUpdated: 'Su valoración se ha actualizado.',

    googleTitle: 'Comparta su experiencia en Google',
    googleBody: 'Si lo desea, también puede dejar una reseña pública en Google.',
    googleAction: 'Continuar a Google',
    googleOpensLabel: '(abre Google)',
    googleHint: 'Abre Google · puede que tenga que iniciar sesión',
    googleUnavailableTitle: 'Google no se puede abrir desde aquí en este momento',
    googleUnavailableBody: 'Su valoración llegó en privado a {name}. Gracias.',
    googleOpenFailed: 'No se pudo abrir Google. Inténtelo de nuevo.',

    noteOfferTitle: 'Añada una nota privada para el equipo',
    noteOfferBody: 'Opcional. Se comparte en privado con {name}.',
    noteOfferAction: 'Escribir una nota privada',
    noteLabel: 'Su nota (opcional)',
    noteHint: 'No es necesario que indique su nombre.',
    noteSend: 'Enviar nota en privado',
    noteDismiss: 'Ahora no',
    noteRequired: 'Escriba su nota antes de enviarla.',
    noteSent: 'Su nota se envió en privado a {name}.',
    noteSendFailed: 'No se pudo enviar su nota. Inténtelo de nuevo.',

    responseTitle: 'Su respuesta',
    responseSummary: 'Cambiar, eliminar o empezar de nuevo',
    responseChangeTitle: 'Cambie su valoración',
    responseChangeSave: 'Guardar la nueva valoración',
    responseRemoveNoteTitle: 'Elimine su nota',
    responseRemoveNoteAction: 'Eliminar',
    responseRemoveNoteDone: 'Su nota se eliminó. Su valoración sigue guardada.',
    responseRemoveNoteFailed: 'No se pudo eliminar su nota. Inténtelo de nuevo.',
    responseRemoveAllTitle: 'Elimine su valoración y su nota',
    responseRemoveAllNote: 'Lo que haya publicado en Google no se ve afectado.',
    responseRemoveAllAction: 'Eliminar…',
    responseRemoveAllConfirmTitle: '¿Eliminar la valoración y la nota?',
    responseRemoveAllConfirmBody: 'Se borrarán ambas. Esta acción no se puede deshacer.',
    responseRemoveAllConfirm: 'Eliminar ambas',
    responseRemoveAllCancel: 'Conservarlas',
    responseRemoveAllDoneTitle: 'Su respuesta se eliminó',
    responseRemoveAllDoneBody: 'Su valoración y, si envió alguna, su nota se borraron.',
    responseRemoveAllFailed: 'No se pudo eliminar su respuesta. Inténtelo de nuevo.',
    responseRemoveRatingTitle: 'Elimine su valoración',
    responseRemoveRatingConfirmTitle: '¿Eliminar la valoración?',
    responseRemoveRatingConfirmBody: 'Se borrará. Esta acción no se puede deshacer.',
    responseRemoveRatingConfirm: 'Eliminarla',
    responseRemoveRatingCancel: 'Conservarla',

    deadlineToday: 'Hasta hoy a las {time}, hora de {zone}',
    deadlineTomorrow: 'Hasta mañana a las {time}, hora de {zone}',
    deadlineDate: 'Hasta el {date}, {time}, hora de {zone}',
    windowEndedChange: 'El plazo para cambiar su valoración ha terminado.',
    windowEndedNote: 'El plazo para eliminar su nota ha terminado.',
    windowEndedAll: 'El plazo para eliminar su respuesta ha terminado.',

    sharedDeviceTitle: '¿Teléfono o tableta compartidos?',
    sharedDeviceBody:
      'Empiece de nuevo para que el siguiente huésped vea una página limpia.',
    startOverAction: 'Empezar de nuevo en este dispositivo',
    startOverDone:
      'Listo para el siguiente huésped. Su respuesta anterior sigue guardada.',
    startOverFailed: 'No se pudo empezar de nuevo. Inténtelo de nuevo.',

    linktreeDefaultTitle: 'Enlaces útiles',
    linkOpensNewTab: '(se abre en una pestaña nueva)',
    unavailableTitle: 'Esta página no está disponible en este momento.',
    unavailableBody: 'Vuelva a intentarlo más tarde.',
  },
  plurals: {
    ratingStars: { one: '{count} estrella', other: '{count} estrellas' },
  },
  zoneNames: {
    UTC: 'UTC',
    'Europe/Sofia': 'Sofía',
    'Europe/London': 'Londres',
    'Europe/Berlin': 'Berlín',
    'Europe/Paris': 'París',
    'Europe/Madrid': 'Madrid',
    'Europe/Rome': 'Roma',
    'Europe/Athens': 'Atenas',
    'Europe/Bucharest': 'Bucarest',
    'Europe/Belgrade': 'Belgrado',
    'Europe/Istanbul': 'Estambul',
    'Europe/Kyiv': 'Kyiv',
    'Europe/Kiev': 'Kyiv',
  },
})
