// Badge context — system-seeded badge library

import type { BadgeSeedDefinitionInput } from './types'

export const SYSTEM_BADGE_DEFINITIONS: readonly BadgeSeedDefinitionInput[] = [
  {
    key: 'first_review',
    name: 'First Review',
    description: 'Earned when a portal receives its first review.',
    icon: 'star',
    targetScope: 'portal',
    criteria: {
      type: 'milestone',
      metricKey: 'portal.rating',
      operator: '>=',
      threshold: 1,
      aggregation: 'count',
    },
  },
  {
    key: 'first_feedback_response',
    name: 'First Feedback Response',
    description: 'Earned when a portal receives its first guest feedback response.',
    icon: 'message-circle',
    targetScope: 'portal',
    criteria: {
      type: 'milestone',
      metricKey: 'portal.feedback',
      operator: '>=',
      threshold: 1,
      aggregation: 'count',
    },
  },
  {
    key: '100_scans',
    name: '100 Scans',
    description: 'Earned when a portal reaches 100 scans.',
    icon: 'scan-line',
    targetScope: 'portal',
    criteria: {
      type: 'threshold',
      metricKey: 'portal.scan',
      operator: '>=',
      threshold: 100,
      aggregation: 'sum',
    },
  },
  {
    key: '500_scans',
    name: '500 Scans',
    description: 'Earned when a portal reaches 500 scans.',
    icon: 'scan',
    targetScope: 'portal',
    criteria: {
      type: 'threshold',
      metricKey: 'portal.scan',
      operator: '>=',
      threshold: 500,
      aggregation: 'sum',
    },
  },
  {
    key: '1000_scans',
    name: '1000 Scans',
    description: 'Earned when a portal reaches 1000 scans.',
    icon: 'sparkles',
    targetScope: 'portal',
    criteria: {
      type: 'threshold',
      metricKey: 'portal.scan',
      operator: '>=',
      threshold: 1000,
      aggregation: 'sum',
    },
  },
  {
    key: '10_feedback_responses',
    name: '10 Feedback Responses',
    description: 'Earned when a portal receives 10 guest feedback responses.',
    icon: 'messages-square',
    targetScope: 'portal',
    criteria: {
      type: 'threshold',
      metricKey: 'portal.feedback',
      operator: '>=',
      threshold: 10,
      aggregation: 'sum',
    },
  },
  {
    key: '50_feedback_responses',
    name: '50 Feedback Responses',
    description: 'Earned when a portal receives 50 guest feedback responses.',
    icon: 'message-square-heart',
    targetScope: 'portal',
    criteria: {
      type: 'threshold',
      metricKey: 'portal.feedback',
      operator: '>=',
      threshold: 50,
      aggregation: 'sum',
    },
  },
  {
    key: 'avg_rating_45_this_month',
    name: '4.5 Avg Rating This Month',
    description: 'Earned when a portal averages at least 4.5 this month.',
    icon: 'medal',
    targetScope: 'portal',
    criteria: {
      type: 'threshold',
      metricKey: 'portal.rating',
      operator: '>=',
      threshold: 4.5,
      aggregation: 'avg',
      period: 'this_month',
    },
  },
  {
    key: '7_day_scan_streak',
    name: '7-Day Scan Streak',
    description: 'Earned when a portal records at least one scan for 7 consecutive days.',
    icon: 'flame',
    targetScope: 'portal',
    criteria: {
      type: 'streak',
      metricKey: 'portal.scan',
      operator: '>=',
      threshold: 1,
      aggregation: 'sum',
      streakDays: 7,
      dailyThreshold: 1,
    },
  },
  {
    key: '5_day_feedback_streak',
    name: '5-Day Feedback Streak',
    description:
      'Earned when a portal records at least one feedback response for 5 consecutive days.',
    icon: 'heart-handshake',
    targetScope: 'portal',
    criteria: {
      type: 'streak',
      metricKey: 'portal.feedback',
      operator: '>=',
      threshold: 1,
      aggregation: 'sum',
      streakDays: 5,
      dailyThreshold: 1,
    },
  },
] as const
