import { describe, expect, it } from 'vitest'
import {
  AI_LANGUAGE_SCRIPT_TABLE_DIGEST,
  evaluateLanguageScriptConsistency,
} from './ai-language-script-consistency'
const PINNED_LANGUAGE_RUNTIME =
  process.versions.unicode === '17.0' && process.versions.icu === '78.2'

const SCRIPT_CASES = [
  ['en-Latn', 'a'],
  ['uk-Cyrl', 'ж'],
  ['ar-Arab', 'ع'],
  ['he-Hebr', 'א'],
  ['hi-Deva', 'क'],
  ['bn-Beng', 'ক'],
  ['ta-Taml', 'அ'],
  ['th-Thai', 'ก'],
  ['zh-Hans', '汉'],
  ['zh-Hant', '漢'],
  ['ja-Jpan', 'あ'],
  ['ja-Jpan', 'ア'],
  ['ja-Jpan', '漢'],
  ['ko-Kore', '가'],
  ['ko-Kore', '漢'],
] as const

describe.runIf(PINNED_LANGUAGE_RUNTIME)('language-script-consistency-v1', () => {
  it.each(SCRIPT_CASES)(
    'accepts the allowed Script_Extensions set for %s',
    (tag, letter) => {
      expect(evaluateLanguageScriptConsistency(letter.repeat(24), tag)).toEqual({
        status: 'consistent',
        letterCount: 24,
        expectedScriptLetterCount: 24,
      })
    },
  )

  it.each([
    [79, 'inconsistent'],
    [80, 'consistent'],
    [81, 'consistent'],
  ] as const)(
    'applies the exact integer 80%% threshold at %i/100',
    (expected, status) => {
      const text = `${'a'.repeat(expected)}${'ж'.repeat(100 - expected)}`
      expect(evaluateLanguageScriptConsistency(text, 'en-Latn')).toMatchObject({
        status,
        letterCount: 100,
        expectedScriptLetterCount: expected,
      })
    },
  )

  it('counts Unicode scalars and ignores marks, digits, emoji, and closed placeholders', () => {
    expect(
      evaluateLanguageScriptConsistency('a\u035c 123 😀 [PERSON]'.repeat(24), 'en-Latn'),
    ).toEqual({ status: 'consistent', letterCount: 24, expectedScriptLetterCount: 24 })
  })

  it('rejects zero-letter input and invalid scalar values', () => {
    expect(evaluateLanguageScriptConsistency('123 😀', 'en-Latn')).toEqual({
      status: 'inconsistent',
      letterCount: 0,
      expectedScriptLetterCount: 0,
    })
    expect(evaluateLanguageScriptConsistency('\ud800', 'en-Latn')).toEqual({
      status: 'policy_unavailable',
    })
  })

  it('exposes a deterministic generated-table digest', () => {
    expect(AI_LANGUAGE_SCRIPT_TABLE_DIGEST).toMatch(/^[a-f0-9]{64}$/)
  })
})

describe.runIf(!PINNED_LANGUAGE_RUNTIME)(
  'language-script-consistency-v1 runtime fence',
  () => {
    it('fails closed before consulting a table generated by another ICU runtime', () => {
      expect(evaluateLanguageScriptConsistency('a'.repeat(24), 'en-Latn')).toEqual({
        status: 'policy_unavailable',
      })
    })
  },
)
