import { describe, expect, it } from 'vitest'
import {
  AI_ZH_ORTHOGRAPHY_PROFILE_DIGEST,
  evaluateZhOrthography,
} from './ai-zh-orthography-verifier'
const PINNED_LANGUAGE_RUNTIME =
  process.versions.unicode === '17.0' && process.versions.icu === '78.2'

describe.runIf(PINNED_LANGUAGE_RUNTIME)('zh-orthography-verifier-v1', () => {
  it('requires at least four decisive Han scalars', () => {
    expect(evaluateZhOrthography('汉语龙马', 'Hans')).toMatchObject({
      status: 'accepted',
    })
    expect(evaluateZhOrthography('汉龙马', 'Hans')).toEqual({
      status: 'insufficient_evidence',
      simplifiedCount: 3,
      traditionalCount: 0,
    })
  })

  it.each([
    [79, 'rejected'],
    [80, 'accepted'],
    [100, 'accepted'],
  ] as const)('applies the exact Hans 80%% ratio at %i/100', (simplified, status) => {
    const text = `${'汉'.repeat(simplified)}${'漢'.repeat(100 - simplified)}`
    expect(evaluateZhOrthography(text, 'Hans')).toMatchObject({
      status,
      simplifiedCount: simplified,
    })
  })

  it('applies the symmetric Hant rule and accepts at most one orthography', () => {
    expect(evaluateZhOrthography('漢語龍馬', 'Hant')).toMatchObject({
      status: 'accepted',
    })
    expect(evaluateZhOrthography('漢語龍馬', 'Hans')).toMatchObject({
      status: 'rejected',
    })
    expect(evaluateZhOrthography('漢漢漢漢汉', 'Hant')).toMatchObject({
      status: 'accepted',
    })
  })

  it('ignores shared Han and non-Han scalars in the decisive denominator', () => {
    expect(evaluateZhOrthography('中人山水的汉语龙马', 'Hans')).toMatchObject({
      status: 'accepted',
      simplifiedCount: 4,
      traditionalCount: 0,
    })
  })

  it('fails closed for invalid Unicode and exposes deterministic profile evidence', () => {
    expect(evaluateZhOrthography('\ud800', 'Hans')).toEqual({
      status: 'policy_unavailable',
    })
    expect(AI_ZH_ORTHOGRAPHY_PROFILE_DIGEST).toMatch(/^[a-f0-9]{64}$/)
  })
})

describe.runIf(!PINNED_LANGUAGE_RUNTIME)(
  'zh-orthography-verifier-v1 runtime fence',
  () => {
    it('fails closed before consulting evidence generated by another ICU runtime', () => {
      expect(evaluateZhOrthography('汉语龙马', 'Hans')).toEqual({
        status: 'policy_unavailable',
      })
    })
  },
)
