// Explicit classification of persisted fields that can carry Google source content,
// provider identifiers, derived data, or similarly named local operational facts.
// The unit test compares this allowlist with the live schema and registered events.

export type ProtectedFieldClassification =
  | 'raw_source_content'
  | 'raw_provider_identifier'
  | 'local_operational_fact'
  | 'derived_metadata'

export type ProtectedFieldRule = readonly [
  relation: string,
  field: string,
  classification: ProtectedFieldClassification,
]

export const PROTECTED_FIELD_REGISTRY = [
  ['reviews', 'external_id', 'raw_provider_identifier'],
  ['review_source_contents', 'external_id', 'raw_provider_identifier'],
  ['review_source_contents', 'external_location_id', 'raw_provider_identifier'],
  ['review_source_contents', 'google_connection_id', 'raw_provider_identifier'],
  ['review_source_contents', 'reviewer_name', 'raw_source_content'],
  ['review_source_contents', 'reviewer_profile_photo_url', 'raw_source_content'],
  ['review_source_contents', 'rating', 'raw_source_content'],
  ['review_source_contents', 'text', 'raw_source_content'],
  ['review_source_contents', 'translated_text', 'raw_source_content'],
  ['review_source_contents', 'language_code', 'raw_source_content'],
  ['review_source_contents', 'reviewed_at', 'raw_source_content'],
  ['review_source_contents', 'content_hash', 'local_operational_fact'],
  ['review_source_contents', 'ai_source_digest', 'local_operational_fact'],
  ['reviews', 'external_location_id', 'raw_provider_identifier'],
  ['reviews', 'google_connection_id', 'raw_provider_identifier'],
  ['reviews', 'reviewer_name', 'raw_source_content'],
  ['reviews', 'reviewer_profile_photo_url', 'raw_source_content'],
  ['reviews', 'rating', 'raw_source_content'],
  ['reviews', 'text', 'raw_source_content'],
  ['reviews', 'language_code', 'raw_source_content'],
  ['reviews', 'content_hash', 'local_operational_fact'],
  ['reviews', 'sentiment_label', 'derived_metadata'],
  ['reviews', 'sentiment_score', 'derived_metadata'],
  ['replies', 'text', 'raw_source_content'],
  ['replies', 'rejection_reason', 'local_operational_fact'],
  ['google_connections', 'google_subject', 'raw_provider_identifier'],
  ['properties', 'google_connection_id', 'raw_provider_identifier'],
  ['properties', 'gbp_account_id', 'raw_provider_identifier'],
  ['properties', 'gbp_location_id', 'raw_provider_identifier'],
  ['properties', 'google_binding_state', 'local_operational_fact'],
  ['properties', 'google_review_uri', 'raw_provider_identifier'],
  ['properties', 'google_review_destination_state', 'local_operational_fact'],
  ['properties', 'google_review_destination_retrieved_at', 'local_operational_fact'],
  ['properties', 'google_review_destination_source_epoch', 'local_operational_fact'],
  ['properties', 'google_review_destination_profile_version', 'local_operational_fact'],
  ['inbox_items', 'snippet', 'raw_source_content'],
  ['inbox_items', 'reviewer_name', 'raw_source_content'],
  ['inbox_items', 'rating', 'raw_source_content'],
  ['inbox_notes', 'text', 'local_operational_fact'],
  ['recent_activity_entries', 'payload', 'local_operational_fact'],
  ['recent_activity_replay_facts', 'transition_payload', 'local_operational_fact'],
  [
    'recent_activity_actor_label_redactions',
    'actor_subject_id',
    'local_operational_fact',
  ],
  ['operational_action_history_records', 'actor_id', 'local_operational_fact'],
  ['operational_action_history_records', 'resource_id', 'local_operational_fact'],
  ['operational_action_history_legal_holds', 'reason_code', 'local_operational_fact'],
  [
    'operational_action_history_legal_holds',
    'placed_by_actor_id',
    'local_operational_fact',
  ],
  [
    'operational_action_history_legal_holds',
    'released_by_actor_id',
    'local_operational_fact',
  ],
  [
    'operational_action_history_legal_holds',
    'release_reason_code',
    'local_operational_fact',
  ],
  ['notifications', 'title', 'local_operational_fact'],
  ['notifications', 'body', 'local_operational_fact'],
  ['notifications', 'payload', 'local_operational_fact'],
  ['outbox_events', 'payload', 'local_operational_fact'],
  ['review_sync_state', 'watermark_source_name', 'raw_provider_identifier'],
  ['inbound_webhook_receipts', 'message_id', 'raw_provider_identifier'],
  ['guest_response_private_feedback', 'body', 'local_operational_fact'],
  ['guest_response_session_bindings', 'session_id', 'local_operational_fact'],
  ['guest_network_pressure_records', 'pseudonym', 'local_operational_fact'],
  ['feedback', 'comment', 'local_operational_fact'],
  ['feedback', 'rating_id', 'local_operational_fact'],
  ['feedback', 'session_id', 'local_operational_fact'],
  ['feedback', 'ip_hash', 'local_operational_fact'],
  ['ratings', 'session_id', 'local_operational_fact'],
  ['ratings', 'ip_hash', 'local_operational_fact'],
  ['scan_events', 'session_id', 'local_operational_fact'],
  ['scan_events', 'ip_hash', 'local_operational_fact'],
  ['guest_destination_action_receipts', 'session_id', 'local_operational_fact'],
  ['guest_qualified_scan_receipts', 'session_id', 'local_operational_fact'],
  ['event:review.created', 'externalId', 'raw_provider_identifier'],
  ['event:review.updated', 'externalId', 'raw_provider_identifier'],
  ['event:property.created', 'name', 'local_operational_fact'],
  ['event:guest.rating.submitted', 'value', 'local_operational_fact'],
] as const satisfies ReadonlyArray<ProtectedFieldRule>
