// PROTOTYPE — the variant registry. Final: the variant agents do not edit this file.
// Each variant file exports its component (VariantA) and its name (VARIANT_A_NAME).
import type {
  PrototypeVariant,
  SettingsPrototypeVariantEntry,
} from '../settings-prototype-types'
import { VARIANT_A_NAME, VariantA } from './settings-prototype-variant-a'
import { VARIANT_B_NAME, VariantB } from './settings-prototype-variant-b'
import { VARIANT_C_NAME, VariantC } from './settings-prototype-variant-c'

export const SETTINGS_PROTOTYPE_VARIANTS: Readonly<
  Record<PrototypeVariant, SettingsPrototypeVariantEntry>
> = {
  A: { Component: VariantA, name: VARIANT_A_NAME },
  B: { Component: VariantB, name: VARIANT_B_NAME },
  C: { Component: VariantC, name: VARIANT_C_NAME },
}
