// Register of intentional DB-only constructs (BQC-5.4).
//
// The migration SQL track is the schema authority (see ../CONTEXT.md). Most
// constructs are ALSO declared in the Drizzle model so the semantic drift
// test (../schema-drift.ts) can verify them against pg_catalog. The objects
// listed here are the ones the Drizzle model deliberately does NOT own —
// either because drizzle-orm 0.45 has no DSL for them (CREATE FUNCTION /
// CREATE TRIGGER) or because they sit on Better Auth–owned tables where two
// migrators must not share DDL ownership.
//
// Rules (enforced both directions by the drift test):
//   - every entry here is verified to EXIST in pg_catalog;
//   - every trigger/function found in pg_catalog must appear here;
//   - entries here are exempt from model-vs-catalog comparison.
//
// To add one: append an entry with an explicit owner + reason, land it via a
// journaled migration (or a registered deploy sidecar applied after
// `pnpm db:migrate`), and keep the entry in sync if the object is dropped.

export type DbOnlyConstructKind =
  | 'trigger'
  | 'function'
  | 'index'
  | 'expression-index'
  | 'partial-index'
  | 'check'
  | 'enum'
  | 'index-direction'
  | 'other'

export type DbOnlyConstruct = Readonly<{
  /** Exact object name as it appears in pg_catalog. */
  name: string
  kind: DbOnlyConstructKind
  /** Owning context (or 'identity' / 'shared'). */
  owner: string
  /** Migration or sidecar path that creates the object. */
  source: string
  /** Why the Drizzle model does not own this construct. */
  reason: string
}>

const DAC_TRIGGERS_SIDECAR =
  'scripts/migrations/2026-07-06-permission-version-triggers.sql'
const NO_TRIGGER_DSL = 'drizzle-orm 0.45 has no CREATE FUNCTION/TRIGGER DSL'

export const DB_ONLY_CONSTRUCTS: readonly DbOnlyConstruct[] = [
  {
    name: 'activity_log',
    kind: 'other',
    owner: 'activity',
    source: 'drizzle/0160_recent_activity_identifiers.sql',
    reason:
      'bounded, automatically updatable rolling-deployment view for older binaries; canonical storage and all current writers use recent_activity_entries',
  },
  {
    name: 'guard_beta_feedback_triage_revision_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0165_beta_feedback_triage.sql',
    reason: `${NO_TRIGGER_DSL}; preserves immutable content-free receipt identity and requires every delivery/triage update to advance the revision exactly once.`,
  },
  {
    name: 'beta_feedback_triage_revision_guard',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0165_beta_feedback_triage.sql',
    reason: `${NO_TRIGGER_DSL}; closes direct-SQL receipt rebinding and revision rollback/jump paths.`,
  },
  {
    name: 'guard_beta_feedback_triage_transition_immutable_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0165_beta_feedback_triage.sql',
    reason: `${NO_TRIGGER_DSL}; rejects rewrites, deletion, and truncation of content-free support transition evidence.`,
  },
  {
    name: 'beta_feedback_triage_transition_update_guard',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0165_beta_feedback_triage.sql',
    reason: `${NO_TRIGGER_DSL}; makes each triage transition row append-only after commit.`,
  },
  {
    name: 'beta_feedback_triage_transition_truncate_guard',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0165_beta_feedback_triage.sql',
    reason: `${NO_TRIGGER_DSL}; prevents bulk removal from bypassing the row-level append-only guard.`,
  },
  {
    name: 'guard_ai_review_analysis_enrollment_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0137_ai_review_analysis_enrollment.sql',
    reason: `${NO_TRIGGER_DSL}; preserves the immutable authorization/snapshot fence and permits only forward enrollment transitions or explicit lifecycle erasure.`,
  },
  {
    name: 'ai_review_analysis_enrollment_guard',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0137_ai_review_analysis_enrollment.sql',
    reason: `${NO_TRIGGER_DSL}; enforces immutable first-enablement authority and terminal evidence.`,
  },
  {
    name: 'guard_ai_review_analysis_enrollment_membership_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0137_ai_review_analysis_enrollment.sql',
    reason: `${NO_TRIGGER_DSL}; admits exact Material Review Revisions only during the canonical snapshot transaction and rejects later mutation.`,
  },
  {
    name: 'ai_review_analysis_enrollment_membership_guard',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0137_ai_review_analysis_enrollment.sql',
    reason: `${NO_TRIGGER_DSL}; makes the unbounded relational Enrollment Coverage Snapshot immutable.`,
  },
  {
    name: 'guard_ai_review_analysis_enrollment_replay_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0137_ai_review_analysis_enrollment.sql',
    reason: `${NO_TRIGGER_DSL}; binds each recovery run to the same tenant, source epoch, capability epoch, and authorization watermark as its enrollment.`,
  },
  {
    name: 'ai_review_analysis_enrollment_replay_guard',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0137_ai_review_analysis_enrollment.sql',
    reason: `${NO_TRIGGER_DSL}; keeps enrollment-to-replay recovery lineage immutable.`,
  },
  {
    name: 'normalize_notification_source_content_v1',
    kind: 'function',
    owner: 'notification',
    source: 'drizzle/0128_notification_source_content_free.sql',
    reason: `${NO_TRIGGER_DSL}; rolling-deployment compatibility normalizes legacy Portal ratings and rejects provider-rating copies before persistence.`,
  },
  {
    name: 'notifications_normalize_source_content',
    kind: 'trigger',
    owner: 'notification',
    source: 'drizzle/0128_notification_source_content_free.sql',
    reason: `${NO_TRIGGER_DSL}; enforces Notification source-content independence for old and current writers.`,
  },
  {
    name: 'fence_google_connector_departure_v1',
    kind: 'function',
    owner: 'integration',
    source: 'drizzle/0124_google_organization_ownership.sql',
    reason: `${NO_TRIGGER_DSL}; atomically fences the current OAuth grant before raw membership removal or AccountAdmin role loss.`,
  },
  {
    name: 'member_fence_google_connector_departure',
    kind: 'trigger',
    owner: 'integration',
    source: 'drizzle/0124_google_organization_ownership.sql',
    reason: `${NO_TRIGGER_DSL}; closes provider-credential offboarding races and Better Auth/support bypass paths.`,
  },
  {
    name: 'reject_inbox_assignment_history_mutation_v1',
    kind: 'function',
    owner: 'inbox',
    source: 'drizzle/0123_inbox_command_revisions.sql',
    reason: `${NO_TRIGGER_DSL}; rejects every rewrite, direct deletion, and truncation of immutable assignment decision history.`,
  },
  {
    name: 'inbox_assignment_history_immutable',
    kind: 'trigger',
    owner: 'inbox',
    source: 'drizzle/0123_inbox_command_revisions.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'inbox_assignment_history_truncate_guard',
    kind: 'trigger',
    owner: 'inbox',
    source: 'drizzle/0123_inbox_command_revisions.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'reject_inbox_escalation_history_mutation_v1',
    kind: 'function',
    owner: 'inbox',
    source: 'drizzle/0169_inbox_escalation_history.sql',
    reason: `${NO_TRIGGER_DSL}; rejects every rewrite, direct deletion, and truncation of immutable escalation decision history.`,
  },
  {
    name: 'inbox_escalation_history_immutable',
    kind: 'trigger',
    owner: 'inbox',
    source: 'drizzle/0169_inbox_escalation_history.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'inbox_escalation_history_truncate_guard',
    kind: 'trigger',
    owner: 'inbox',
    source: 'drizzle/0169_inbox_escalation_history.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'enforce_inbox_feedback_handling_outcome_append_v1',
    kind: 'function',
    owner: 'inbox',
    source: 'drizzle/0141_private_feedback_handling_outcomes.sql',
    reason: `${NO_TRIGGER_DSL}; binds manager outcomes to private-feedback completion and preserves the first completion facts across corrections.`,
  },
  {
    name: 'inbox_feedback_handling_outcomes_append_guard',
    kind: 'trigger',
    owner: 'inbox',
    source: 'drizzle/0141_private_feedback_handling_outcomes.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'reject_inbox_feedback_handling_outcome_mutation_v1',
    kind: 'function',
    owner: 'inbox',
    source: 'drizzle/0141_private_feedback_handling_outcomes.sql',
    reason: `${NO_TRIGGER_DSL}; preserves every manager outcome correction while permitting aggregate lifecycle cleanup through the stable Inbox Item.`,
  },
  {
    name: 'inbox_feedback_handling_outcomes_immutable',
    kind: 'trigger',
    owner: 'inbox',
    source: 'drizzle/0141_private_feedback_handling_outcomes.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'inbox_feedback_handling_outcomes_truncate_guard',
    kind: 'trigger',
    owner: 'inbox',
    source: 'drizzle/0141_private_feedback_handling_outcomes.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'enforce_inbox_response_target_terminal_v1',
    kind: 'function',
    owner: 'inbox',
    source: 'drizzle/0158_inbox_response_targets.sql',
    reason: `${NO_TRIGGER_DSL}; preserves each cycle's policy/time snapshot and permits only its first terminal result or aggregate lifecycle cascade.`,
  },
  {
    name: 'inbox_handling_cycle_response_targets_terminal_guard',
    kind: 'trigger',
    owner: 'inbox',
    source: 'drizzle/0158_inbox_response_targets.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'validate_inbox_response_target_reminder_schedule_v1',
    kind: 'function',
    owner: 'inbox',
    source: 'drizzle/0158_inbox_response_targets.sql',
    reason: `${NO_TRIGGER_DSL}; binds the two reminder slots to the exact immutable halfway and due instants of their measured target snapshot.`,
  },
  {
    name: 'inbox_response_target_reminders_schedule_guard',
    kind: 'trigger',
    owner: 'inbox',
    source: 'drizzle/0158_inbox_response_targets.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'enforce_inbox_response_target_reminder_terminal_v1',
    kind: 'function',
    owner: 'inbox',
    source: 'drizzle/0158_inbox_response_targets.sql',
    reason: `${NO_TRIGGER_DSL}; makes each halfway/target-passed slot one-shot while retaining aggregate lifecycle cleanup.`,
  },
  {
    name: 'inbox_response_target_reminders_terminal_guard',
    kind: 'trigger',
    owner: 'inbox',
    source: 'drizzle/0158_inbox_response_targets.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'reject_inbox_response_target_truncate_v1',
    kind: 'function',
    owner: 'inbox',
    source: 'drizzle/0158_inbox_response_targets.sql',
    reason: `${NO_TRIGGER_DSL}; prevents bulk removal of target and reminder history.`,
  },
  {
    name: 'inbox_handling_cycle_response_targets_truncate_guard',
    kind: 'trigger',
    owner: 'inbox',
    source: 'drizzle/0158_inbox_response_targets.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'inbox_response_target_reminders_truncate_guard',
    kind: 'trigger',
    owner: 'inbox',
    source: 'drizzle/0158_inbox_response_targets.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'reject_reply_publication_authorization_mutation_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0122_reply_google_observation_truth.sql',
    reason: `${NO_TRIGGER_DSL}; rejects every rewrite, direct deletion, and truncation of immutable manager publication authority evidence.`,
  },
  {
    name: 'reply_publication_authorizations_immutable',
    kind: 'trigger',
    owner: 'review',
    source: 'drizzle/0122_reply_google_observation_truth.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'reply_publication_authorizations_truncate_guard',
    kind: 'trigger',
    owner: 'review',
    source: 'drizzle/0122_reply_google_observation_truth.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'mirror_legacy_ai_review_backfill_memberships_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0119_ai_review_backfill_relational_membership.sql',
    reason: `${NO_TRIGGER_DSL}; expand-phase mirror for old binaries that still insert the retained review_ids compatibility array.`,
  },
  {
    name: 'ai_review_backfill_legacy_membership_mirror',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0119_ai_review_backfill_relational_membership.sql',
    reason: `${NO_TRIGGER_DSL}; atomically creates canonical membership for old-binary run inserts during rolling deployment.`,
  },
  {
    name: 'guard_ai_review_backfill_membership_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0137_ai_review_analysis_enrollment.sql',
    reason: `${NO_TRIGGER_DSL}; admits rows only while a run is opening, requires an exact Material Review Revision for first-enablement runs, rejects rewrites/direct deletes, and preserves owning-run lifecycle cascades.`,
  },
  {
    name: 'ai_review_backfill_membership_immutable',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0119_ai_review_backfill_relational_membership.sql',
    reason: `${NO_TRIGGER_DSL}; relational run membership is immutable after the opening transaction.`,
  },
  {
    name: 'reject_inbox_handling_cycle_update_v1',
    kind: 'function',
    owner: 'inbox',
    source: 'drizzle/0117_inbox_handling_cycles_expand.sql',
    reason: `${NO_TRIGGER_DSL}; prevents immutable Handling Cycle opening facts from being rewritten while retaining cascade cleanup of the stable Inbox Item.`,
  },
  {
    name: 'inbox_handling_cycles_immutable',
    kind: 'trigger',
    owner: 'inbox',
    source: 'drizzle/0117_inbox_handling_cycles_expand.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'inbox_handling_cycles_manual_reopen_valid',
    kind: 'check',
    owner: 'inbox',
    source: 'drizzle/0129_inbox_governed_manual_reopen.sql',
    reason:
      'drizzle-orm 0.45 cannot declare a CHECK as NOT VALID; the migration deliberately fences new writes without validating or inferring governed reasons for immutable legacy cycles. The model retains the intended expression while drift still requires the database constraint to exist.',
  },
  {
    name: 'google_connections_credential_home_pair_check',
    kind: 'check',
    owner: 'integration',
    source: 'drizzle/0133_google_credential_routing_authority.sql',
    reason:
      'drizzle-orm 0.45 cannot declare a CHECK as NOT VALID; 0133 fences every new write while the explicit digest-bound legacy credential-home backfill remains pending.',
  },
  {
    name: 'google_connections_credential_home_value_check',
    kind: 'check',
    owner: 'integration',
    source: 'drizzle/0133_google_credential_routing_authority.sql',
    reason:
      'drizzle-orm 0.45 cannot declare a CHECK as NOT VALID; 0133 validates all new home/policy/generation triples without inferring values for legacy grants.',
  },
  {
    name: 'guard_portal_publication_history_v1',
    kind: 'function',
    owner: 'portal',
    source: 'drizzle/0115_portal_publication_immutability.sql',
    reason: `${NO_TRIGGER_DSL}; prevents publication snapshots and effective-dated activation rows from being rewritten after commit while retaining explicit erase/fixture cleanup paths.`,
  },
  {
    name: 'is_current_portal_ai_reply_brand_profile_v1',
    kind: 'function',
    owner: 'portal',
    source: 'drizzle/0163_ai_reply_brand_profile_grounding.sql',
    reason: `${NO_TRIGGER_DSL}; gives the database admission authority a boolean, transaction-bound public display-name version/digest check without exposing Portal content.`,
  },
  {
    name: 'portal_publication_snapshots_immutable',
    kind: 'trigger',
    owner: 'portal',
    source: 'drizzle/0115_portal_publication_immutability.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'portal_publication_activations_history_guard',
    kind: 'trigger',
    owner: 'portal',
    source: 'drizzle/0115_portal_publication_immutability.sql',
    reason: `${NO_TRIGGER_DSL}; permits only the one-time close of a current activation interval.`,
  },
  {
    name: 'guard_organization_lifecycle_revision_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0159_organization_lifecycle_authority.sql',
    reason: `${NO_TRIGGER_DSL}; makes the Organization lifecycle revision advance exactly once per transition while preserving its tenant binding.`,
  },
  {
    name: 'organization_lifecycle_revision_guard',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0159_organization_lifecycle_authority.sql',
    reason: `${NO_TRIGGER_DSL}; closes direct-SQL revision rollback, jump, and tenant-rebind paths.`,
  },
  {
    name: 'guard_organization_lifecycle_policy_fence_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0159_organization_lifecycle_authority.sql',
    reason: `${NO_TRIGGER_DSL}; prevents generic policy administration from clearing the fail-closed Organization suspension before explicit reactivation.`,
  },
  {
    name: 'organization_lifecycle_policy_fence',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0159_organization_lifecycle_authority.sql',
    reason: `${NO_TRIGGER_DSL}; keeps pending and canceled closure lineages suspended across every organization_policy write path.`,
  },
  {
    name: 'provision_organization_lifecycle_authority_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0159_organization_lifecycle_authority.sql',
    reason: `${NO_TRIGGER_DSL}; provisions the app-owned lifecycle authority atomically for every Better Auth Organization insert.`,
  },
  {
    name: 'organization_lifecycle_authority_provision',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0159_organization_lifecycle_authority.sql',
    reason: `${NO_TRIGGER_DSL}; removes route-specific provisioning gaps for Organizations created after the lifecycle migration.`,
  },
  {
    name: 'guard_organization_export_revision_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0170_organization_export_pre_egress_evidence.sql',
    reason: `${NO_TRIGGER_DSL}; preserves the export request binding, forward-only state machine, exact revision, write-once pre-egress and archive checksum evidence, and a co-committed append-only retrieval issuance.`,
  },
  {
    name: 'reject_context_lifecycle_receipt_mutation_v1',
    kind: 'function',
    owner: 'shared',
    source: 'drizzle/0171_context_organization_lifecycle_receipts.sql',
    reason: `${NO_TRIGGER_DSL}; makes the shared per-context lifecycle phase receipts append-only after commit.`,
  },
  {
    name: 'context_organization_lifecycle_receipts_update_delete_guard',
    kind: 'trigger',
    owner: 'shared',
    source: 'drizzle/0171_context_organization_lifecycle_receipts.sql',
    reason: `${NO_TRIGGER_DSL}; prevents a failed phase from being presented as complete by rewriting or removing its receipt.`,
  },
  {
    name: 'context_organization_lifecycle_receipts_truncate_guard',
    kind: 'trigger',
    owner: 'shared',
    source: 'drizzle/0171_context_organization_lifecycle_receipts.sql',
    reason: `${NO_TRIGGER_DSL}; prevents bulk removal from bypassing shared lifecycle receipt immutability.`,
  },
  {
    name: 'reject_backup_erasure_ledger_mutation_v1',
    kind: 'function',
    owner: 'shared',
    source: 'drizzle/0172_backup_erasure_ledger.sql',
    reason: `${NO_TRIGGER_DSL}; makes the backup-erasure ledger and its hold releases append-only after commit.`,
  },
  {
    name: 'backup_erasure_ledger_update_delete_guard',
    kind: 'trigger',
    owner: 'shared',
    source: 'drizzle/0172_backup_erasure_ledger.sql',
    reason: `${NO_TRIGGER_DSL}; a rewritable entry could be removed after a bad restore, which is exactly the resurrection this ledger prevents.`,
  },
  {
    name: 'backup_erasure_ledger_truncate_guard',
    kind: 'trigger',
    owner: 'shared',
    source: 'drizzle/0172_backup_erasure_ledger.sql',
    reason: `${NO_TRIGGER_DSL}; prevents bulk removal from bypassing ledger immutability.`,
  },
  {
    name: 'backup_erasure_hold_releases_update_delete_guard',
    kind: 'trigger',
    owner: 'shared',
    source: 'drizzle/0172_backup_erasure_ledger.sql',
    reason: `${NO_TRIGGER_DSL}; a released legal hold is an irreversible authorization to re-apply an erasure and must not be retracted by UPDATE.`,
  },
  {
    name: 'backup_erasure_hold_releases_truncate_guard',
    kind: 'trigger',
    owner: 'shared',
    source: 'drizzle/0172_backup_erasure_ledger.sql',
    reason: `${NO_TRIGGER_DSL}; prevents bulk removal from bypassing hold-release immutability.`,
  },
  {
    name: 'reject_property_erase_authority_mutation_v1',
    kind: 'function',
    owner: 'property',
    source: 'drizzle/0173_property_erase_authority.sql',
    reason: `${NO_TRIGGER_DSL}; enforces the one-way purge_pending -> purging -> purged boundary and keeps the support authorization binding immutable.`,
  },
  {
    name: 'property_erase_authorities_transition_guard',
    kind: 'trigger',
    owner: 'property',
    source: 'drizzle/0173_property_erase_authority.sql',
    reason: `${NO_TRIGGER_DSL}; refuses cancellation once purging has begun — the irreversible boundary must hold against direct SQL, not only the domain table.`,
  },
  {
    name: 'property_erase_authorities_truncate_guard',
    kind: 'trigger',
    owner: 'property',
    source: 'drizzle/0173_property_erase_authority.sql',
    reason: `${NO_TRIGGER_DSL}; prevents bulk removal of erase authority evidence.`,
  },
  {
    name: 'property_erase_context_receipts_mutation_guard',
    kind: 'trigger',
    owner: 'property',
    source: 'drizzle/0173_property_erase_authority.sql',
    reason: `${NO_TRIGGER_DSL}; per-context purge receipts are the replay ledger an interrupted job resumes from and must be append-only.`,
  },
  {
    name: 'property_erase_context_receipts_truncate_guard',
    kind: 'trigger',
    owner: 'property',
    source: 'drizzle/0173_property_erase_authority.sql',
    reason: `${NO_TRIGGER_DSL}; prevents bulk removal from bypassing receipt immutability.`,
  },
  {
    name: 'reject_privacy_request_mutation_v1',
    kind: 'function',
    owner: 'shared',
    source: 'drizzle/0174_privacy_requests.sql',
    reason: `${NO_TRIGGER_DSL}; enforces the received -> verified -> in_progress -> fulfilled|refused state machine and makes its transition history append-only.`,
  },
  {
    name: 'privacy_requests_transition_guard',
    kind: 'trigger',
    owner: 'shared',
    source: 'drizzle/0174_privacy_requests.sql',
    reason: `${NO_TRIGGER_DSL}; no edge may skip identity verification, including through direct SQL.`,
  },
  {
    name: 'privacy_requests_truncate_guard',
    kind: 'trigger',
    owner: 'shared',
    source: 'drizzle/0174_privacy_requests.sql',
    reason: `${NO_TRIGGER_DSL}; prevents bulk removal of privacy request evidence.`,
  },
  {
    name: 'privacy_request_transitions_mutation_guard',
    kind: 'trigger',
    owner: 'shared',
    source: 'drizzle/0174_privacy_requests.sql',
    reason: `${NO_TRIGGER_DSL}; rejects rewrites and deletion of append-only privacy transition evidence.`,
  },
  {
    name: 'privacy_request_transitions_truncate_guard',
    kind: 'trigger',
    owner: 'shared',
    source: 'drizzle/0174_privacy_requests.sql',
    reason: `${NO_TRIGGER_DSL}; prevents bulk removal from bypassing transition immutability.`,
  },
  {
    name: 'organization_export_revision_guard',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0159_organization_lifecycle_authority.sql',
    reason: `${NO_TRIGGER_DSL}; rejects direct-SQL export rollback, rebinding, and archive-evidence substitution.`,
  },
  {
    name: 'reject_identity_lifecycle_evidence_mutation_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0168_identity_organization_lifecycle_receipts.sql',
    reason: `${NO_TRIGGER_DSL}; makes lifecycle phase receipts and retrieval issuance evidence append-only after commit.`,
  },
  {
    name: 'identity_organization_lifecycle_receipts_update_delete_guard',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0168_identity_organization_lifecycle_receipts.sql',
    reason: `${NO_TRIGGER_DSL}; prevents replay evidence from being rewritten or removed so phase work cannot be repeated by tampering.`,
  },
  {
    name: 'identity_organization_lifecycle_receipts_truncate_guard',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0168_identity_organization_lifecycle_receipts.sql',
    reason: `${NO_TRIGGER_DSL}; prevents bulk removal from bypassing lifecycle receipt immutability.`,
  },
  {
    name: 'organization_export_retrieval_issuances_update_delete_guard',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0168_identity_organization_lifecycle_receipts.sql',
    reason: `${NO_TRIGGER_DSL}; keeps every expired or consumed retrieval digest permanently unavailable for the request.`,
  },
  {
    name: 'organization_export_retrieval_issuances_truncate_guard',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0168_identity_organization_lifecycle_receipts.sql',
    reason: `${NO_TRIGGER_DSL}; prevents bulk removal from resurrecting historical retrieval tokens.`,
  },
  {
    name: 'guard_organization_export_retrieval_issuance_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0168_identity_organization_lifecycle_receipts.sql',
    reason: `${NO_TRIGGER_DSL}; binds a new issuance to the locked export head, next revision, tenant, object lifetime, and allowed ready/expired state.`,
  },
  {
    name: 'organization_export_retrieval_issuance_insert_guard',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0168_identity_organization_lifecycle_receipts.sql',
    reason: `${NO_TRIGGER_DSL}; rejects direct-SQL issuance history that is not authorized by the current export head.`,
  },
  {
    name: 'verify_organization_export_retrieval_issuance_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0168_identity_organization_lifecycle_receipts.sql',
    reason: `${NO_TRIGGER_DSL}; verifies at commit that an issuance receipt and the mutable export head changed together.`,
  },
  {
    name: 'organization_export_retrieval_issuance_commit_guard',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0168_identity_organization_lifecycle_receipts.sql',
    reason: `${NO_TRIGGER_DSL}; prevents orphan issuance history from poisoning a future valid revision.`,
  },
  {
    name: 'guard_identity_invitation_fact_contract_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0106_identity_invitation_fact_expand.sql',
    reason: `${NO_TRIGGER_DSL}; serializes rolling v1/v2 invitation-fact issuance and rejects legacy PII writers after cutover.`,
  },
  {
    name: 'identity_invitation_fact_contract_guard',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0106_identity_invitation_fact_expand.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'guard_property_data_cell_assignment_v1',
    kind: 'function',
    owner: 'property',
    source: 'drizzle/0140_single_us_beta_data_cell.sql',
    reason: `${NO_TRIGGER_DSL}; preserves assignment immutability and pins resolved writes to the single-US beta target while the durable cutover is fenced or complete.`,
  },
  {
    name: 'single_us_beta_supported_country_v3',
    kind: 'function',
    owner: 'shared',
    source: 'drizzle/0140_single_us_beta_data_cell.sql',
    reason: `${NO_TRIGGER_DSL}; freezes the exact catalogue-policy-v3 country set used by the database cutover guard.`,
  },
  {
    name: 'guard_data_cell_topology_cutover_work_v1',
    kind: 'function',
    owner: 'shared',
    source: 'drizzle/0140_single_us_beta_data_cell.sql',
    reason: `${NO_TRIGGER_DSL}; serializes every nonterminal workflow admission against the durable topology-cutover fence.`,
  },
  ...[
    'region_moves_topology_cutover_fence',
    'gbp_import_jobs_topology_cutover_fence',
    'legacy_import_effect_leases_topology_cutover_fence',
    'gbp_import_requests_topology_cutover_fence',
    'gbp_import_request_items_topology_cutover_fence',
    'gbp_import_request_item_retries_topology_cutover_fence',
    'authorization_execution_permits_topology_cutover_fence',
    'google_credential_source_operations_topology_cutover_fence',
    'credential_revoke_permits_topology_cutover_fence',
    'google_subject_authority_guards_topology_cutover_fence',
    'google_subject_authority_pointer_topology_cutover_fence',
    'google_credential_broker_replay_topology_cutover_fence',
    'google_connections_cleanup_topology_cutover_fence',
  ].map((name): DbOnlyConstruct => ({
    name,
    kind: 'trigger',
    owner: 'shared',
    source: 'drizzle/0140_single_us_beta_data_cell.sql',
    reason: `${NO_TRIGGER_DSL}; refuses a new nonterminal cutover blocker while the shared topology fence is active.`,
  })),
  {
    name: 'guard_single_us_credential_home_v1',
    kind: 'function',
    owner: 'integration',
    source: 'drizzle/0140_single_us_beta_data_cell.sql',
    reason: `${NO_TRIGGER_DSL}; pins current Google credential-home facts to US policy 3 during and after the cutover.`,
  },
  ...[
    'google_organization_credential_homes_topology_cutover_fence',
    'google_connections_home_topology_cutover_fence',
  ].map((name): DbOnlyConstruct => ({
    name,
    kind: 'trigger',
    owner: 'integration',
    source: 'drizzle/0140_single_us_beta_data_cell.sql',
    reason: `${NO_TRIGGER_DSL}; enforces the completed single-US credential-home topology.`,
  })),
  {
    name: 'properties_data_cell_assignment_guard',
    kind: 'trigger',
    owner: 'property',
    source: 'drizzle/0089_property-data-cell-expand.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'properties_data_cell_assignment_insert',
    kind: 'trigger',
    owner: 'property',
    source: 'drizzle/0091_property-data-cell-rolling-writes.sql',
    reason: `${NO_TRIGGER_DSL}; dual-writes the canonical assignment for legacy replicas during the expand rollout.`,
  },
  {
    name: 'organization_role_org_role_lower_unique',
    kind: 'expression-index',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason:
      'Unique index on Better Auth–owned "organizationRole" (organizationId, lower(role)); ' +
      'two migrators cannot share DDL ownership and drizzle-kit must not manage BA tables.',
  },
  {
    name: 'bump_permission_version',
    kind: 'function',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: `${NO_TRIGGER_DSL}; upsert helper for the permission_version counter.`,
  },
  {
    name: 'tgr_bump_perm_ba',
    kind: 'function',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: `${NO_TRIGGER_DSL}; AFTER-row trigger fn for BA-owned tables (camelCase "organizationId").`,
  },
  {
    name: 'tgr_bump_perm_app',
    kind: 'function',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: `${NO_TRIGGER_DSL}; AFTER-row trigger fn for app-owned tables (snake_case organization_id).`,
  },
  {
    name: 'guard_last_owner',
    kind: 'function',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: `${NO_TRIGGER_DSL}; last-owner backstop for direct-DB writes to member.`,
  },
  {
    name: 'member_perm_ver_ins',
    kind: 'trigger',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'member_perm_ver_del',
    kind: 'trigger',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'member_perm_ver_upd',
    kind: 'trigger',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'organization_role_perm_ver_iud',
    kind: 'trigger',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'organization_role_policy_perm_ver_iud',
    kind: 'trigger',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'staff_assignments_perm_ver_iud',
    kind: 'trigger',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'property_access_grant_perm_ver_iud',
    kind: 'trigger',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: `${NO_TRIGGER_DSL}; serializes canonical assigned-Property grant changes with permission-sensitive delayed commands.`,
  },
  {
    name: 'member_last_owner_del',
    kind: 'trigger',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'member_last_owner_upd',
    kind: 'trigger',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'tm_no_overlapping_participation_intervals',
    kind: 'index',
    owner: 'team',
    source: 'drizzle/0020_people-team-expansion.sql',
    reason:
      'Backing index for an EXCLUDE USING gist constraint; Drizzle has no exclusion-constraint DSL.',
  },
  {
    name: 'pr_no_overlapping_responsibility_intervals',
    kind: 'index',
    owner: 'staff',
    source: 'drizzle/0020_people-team-expansion.sql',
    reason:
      'Backing index for an EXCLUDE USING gist constraint; Drizzle has no exclusion-constraint DSL.',
  },
  {
    name: 'pr_no_overlapping_primary_intervals',
    kind: 'index',
    owner: 'staff',
    source: 'drizzle/0130_primary_staff_event_attribution.sql',
    reason:
      'Backing index for the Portal-wide Primary Staff interval exclusion; Drizzle has no exclusion-constraint DSL.',
  },
  {
    name: 'guard_primary_staff_attribution_immutable_v1',
    kind: 'function',
    owner: 'guest',
    source: 'drizzle/0130_primary_staff_event_attribution.sql',
    reason: `${NO_TRIGGER_DSL}; prevents future Staff reassignment from rewriting Guest facts or Metric projections.`,
  },
  {
    name: 'guest_qualified_scans_staff_attribution_immutable',
    kind: 'trigger',
    owner: 'guest',
    source: 'drizzle/0130_primary_staff_event_attribution.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'guest_responses_staff_attribution_immutable',
    kind: 'trigger',
    owner: 'guest',
    source: 'drizzle/0130_primary_staff_event_attribution.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'metric_readings_staff_attribution_immutable',
    kind: 'trigger',
    owner: 'metric',
    source: 'drizzle/0130_primary_staff_event_attribution.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'metric_corrections_staff_attribution_immutable',
    kind: 'trigger',
    owner: 'metric',
    source: 'drizzle/0130_primary_staff_event_attribution.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'tpgs_no_overlapping_scope_intervals',
    kind: 'index',
    owner: 'team',
    source: 'drizzle/0020_people-team-expansion.sql',
    reason:
      'Backing index for an EXCLUDE USING gist constraint; Drizzle has no exclusion-constraint DSL.',
  },
  {
    name: 'pgm_no_overlapping_portal_intervals',
    kind: 'index',
    owner: 'portal',
    source: 'drizzle/0020_people-team-expansion.sql',
    reason:
      'Backing index for an EXCLUDE USING gist constraint; Drizzle has no exclusion-constraint DSL.',
  },
  {
    name: 'reject_goal_immutable_update',
    kind: 'function',
    owner: 'goal',
    source: 'drizzle/0024_goal-versioning.sql',
    reason: `${NO_TRIGGER_DSL}; rejects updates and deletes on governed goal facts.`,
  },
  {
    name: 'goal_definition_versions_immutable',
    kind: 'trigger',
    owner: 'goal',
    source: 'drizzle/0024_goal-versioning.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'goal_evaluations_immutable',
    kind: 'trigger',
    owner: 'goal',
    source: 'drizzle/0024_goal-versioning.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'gpv_no_overlapping_effective_intervals',
    kind: 'index',
    owner: 'goal',
    source: 'drizzle/0087_harden-canonical-goal-programs.sql',
    reason:
      'Backing index for the Goal Program version EXCLUDE USING gist constraint; Drizzle has no exclusion-constraint DSL.',
  },
  {
    name: 'gsa_no_overlapping_subject_metric_intervals',
    kind: 'index',
    owner: 'goal',
    source: 'drizzle/0087_harden-canonical-goal-programs.sql',
    reason:
      'Backing index preventing overlapping Goal assignments for the same subject and metric; Drizzle has no exclusion-constraint DSL.',
  },
  {
    name: 'reject_canonical_goal_append_only_mutation_v1',
    kind: 'function',
    owner: 'goal',
    source: 'drizzle/0087_harden-canonical-goal-programs.sql',
    reason: `${NO_TRIGGER_DSL}; protects immutable Goal Program versions (apart from one temporal-window closure) and fully immutable result revisions.`,
  },
  {
    name: 'goal_program_versions_append_only',
    kind: 'trigger',
    owner: 'goal',
    source: 'drizzle/0087_harden-canonical-goal-programs.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'goal_result_revisions_append_only',
    kind: 'trigger',
    owner: 'goal',
    source: 'drizzle/0087_harden-canonical-goal-programs.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'guard_goal_program_transition_v1',
    kind: 'function',
    owner: 'goal',
    source: 'drizzle/0088_allow-ending-scheduled-goal-programs.sql',
    reason: `${NO_TRIGGER_DSL}; enforces the canonical Goal Program lifecycle and monotonic version head.`,
  },
  {
    name: 'goal_programs_transition_guard',
    kind: 'trigger',
    owner: 'goal',
    source: 'drizzle/0087_harden-canonical-goal-programs.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'guard_goal_monthly_result_v1',
    kind: 'function',
    owner: 'goal',
    source: 'drizzle/0087_harden-canonical-goal-programs.sql',
    reason: `${NO_TRIGGER_DSL}; enforces monthly calendar bounds, assignment/version windows, lifecycle order, reconciliation delay, and closed-result immutability.`,
  },
  {
    name: 'goal_monthly_results_guard',
    kind: 'trigger',
    owner: 'goal',
    source: 'drizzle/0087_harden-canonical-goal-programs.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'validate_goal_result_revision_v1',
    kind: 'function',
    owner: 'goal',
    source: 'drizzle/0087_harden-canonical-goal-programs.sql',
    reason: `${NO_TRIGGER_DSL}; serializes and validates direct append-only correction lineage for closed monthly results.`,
  },
  {
    name: 'goal_result_revisions_insert_guard',
    kind: 'trigger',
    owner: 'goal',
    source: 'drizzle/0087_harden-canonical-goal-programs.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'reject_recognition_immutable_mutation',
    kind: 'function',
    owner: 'recognition',
    source: 'drizzle/0025_recognition-governance.sql',
    reason: `${NO_TRIGGER_DSL}; rejects updates and deletes on governed recognition facts.`,
  },
  {
    name: 'recognition_board_snapshots_append_only',
    kind: 'trigger',
    owner: 'recognition',
    source: 'drizzle/0025_recognition-governance.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'recognition_board_entries_append_only',
    kind: 'trigger',
    owner: 'recognition',
    source: 'drizzle/0025_recognition-governance.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'recognition_reconciliation_events_append_only',
    kind: 'trigger',
    owner: 'recognition',
    source: 'drizzle/0025_recognition-governance.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'badge_definition_versions_append_only',
    kind: 'trigger',
    owner: 'recognition',
    source: 'drizzle/0025_recognition-governance.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'recognition_awards_append_only',
    kind: 'trigger',
    owner: 'recognition',
    source: 'drizzle/0025_recognition-governance.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'recognition_award_status_facts_append_only',
    kind: 'trigger',
    owner: 'recognition',
    source: 'drizzle/0025_recognition-governance.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'reject_capability_compliance_approval_mutation',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0029_google-content-control.sql',
    reason: `${NO_TRIGGER_DSL}; rejects in-place mutation of signed approval bindings.`,
  },
  {
    name: 'capability_compliance_approvals_append_only',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0029_google-content-control.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_epoch_millis_v1',
    kind: 'function',
    owner: 'shared',
    source: 'drizzle/0043_review-source-provenance.sql',
    reason: `${NO_TRIGGER_DSL}; exact PostgreSQL epoch-millisecond conversion used by AI source authorization.`,
  },
  {
    name: 'ai_advisory_lock_key_v1',
    kind: 'function',
    owner: 'shared',
    source: 'drizzle/0043_review-source-provenance.sql',
    reason: `${NO_TRIGGER_DSL}; domain-separated advisory-lock key derivation for AI and provider workflows.`,
  },
  {
    name: 'lock_review_ai_analysis_head_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0043_review-source-provenance.sql',
    reason: `${NO_TRIGGER_DSL}; atomically validates the source epoch and allocates a review analysis sequence.`,
  },
  {
    name: 'reposition_merchant_ai_analysis_watermark_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0074_ai-backfill-consent-lineage.sql',
    reason: `${NO_TRIGGER_DSL}; repositions the merchant review-analysis watermark and bumps the analysis epoch in one transaction, so an audited backfill cannot leave the watermark and the epoch disagreeing, and derives the consent-evidence actor from the latest merchant consent decision in the lineage — never from another analysis_backfill row — so the ledger names an accountable member rather than the operator.`,
  },
  {
    name: 'initialize_review_provider_subject_hmac_key_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0043_review-source-provenance.sql',
    reason: `${NO_TRIGGER_DSL}; initializes the provider-subject HMAC key inventory under an advisory lock.`,
  },
  {
    name: 'review_provider_subject_hmac_key_inventory_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0043_review-source-provenance.sql',
    reason: `${NO_TRIGGER_DSL}; exposes only the content-free provider-subject key inventory.`,
  },
  {
    name: 'trust_next_review_provider_subject_hmac_key_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0043_review-source-provenance.sql',
    reason: `${NO_TRIGGER_DSL}; stages one trusted-next provider-subject key under a generation fence.`,
  },
  {
    name: 'rotate_review_provider_subject_hmac_key_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0043_review-source-provenance.sql',
    reason: `${NO_TRIGGER_DSL}; atomically promotes trusted-next and retires the prior provider-subject key.`,
  },
  {
    name: 'remove_review_provider_subject_hmac_key_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0043_review-source-provenance.sql',
    reason: `${NO_TRIGGER_DSL}; removes a retired key only after no provider-subject mapping references it.`,
  },
  {
    name: 'assert_ai_capability_set_executable_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0044_merchant-ai-authorization.sql',
    reason: `${NO_TRIGGER_DSL}; fail-closed merchant AI capability-to-runtime catalogue validation.`,
  },
  {
    name: 'guard_merchant_ai_evidence_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0044_merchant-ai-authorization.sql',
    reason: `${NO_TRIGGER_DSL}; append-only consent-evidence transition guard.`,
  },
  {
    name: 'merchant_ai_consent_evidence_append_guard',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0044_merchant-ai-authorization.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'merchant_ai_consent_evidence_truncate_guard',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0044_merchant-ai-authorization.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'guard_merchant_ai_enablement_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0044_merchant-ai-authorization.sql',
    reason: `${NO_TRIGGER_DSL}; validates the mutable authorization head against immutable evidence.`,
  },
  {
    name: 'merchant_ai_enablement_transition_guard',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0044_merchant-ai-authorization.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'merchant_ai_enablement_truncate_guard',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0044_merchant-ai-authorization.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'apply_merchant_ai_transition_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0060_ai-plane-source-epoch-zero.sql',
    reason: `${NO_TRIGGER_DSL}; serializes merchant AI authorization, source epoch, and analysis watermark transitions. Introduced in 0045; 0060 relaxed its authorized-source-epoch guard to the domain's 0-based numbering.`,
  },
  {
    name: 'assert_ai_runtime_catalogue_ready_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0163_ai_reply_brand_profile_grounding.sql',
    reason: `${NO_TRIGGER_DSL}; verifies the complete immutable runtime catalogue at readiness. Introduced in 0046; re-emitted whenever the catalogue projection it byte-compares moves, most recently for Brand Profile-grounded Reply Drafting.`,
  },
  {
    name: 'reject_ai_catalogue_mutation_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: `${NO_TRIGGER_DSL}; rejects mutation of immutable AI catalogues and control history.`,
  },
  {
    name: 'ai_property_local_date_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0047_ai-derivatives-and-property-calendar.sql',
    reason: `${NO_TRIGGER_DSL}; sole versioned reviewed-at to property-local-date conversion.`,
  },
  {
    name: 'ai_provider_profiles_immutable',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_provider_profiles_no_truncate',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_routing_policies_immutable',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_routing_policies_no_truncate',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_operation_profiles_immutable',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_operation_profiles_no_truncate',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_control_history_immutable',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_control_history_no_truncate',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_property_calendar_catalogues_immutable',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0047_ai-derivatives-and-property-calendar.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_property_calendar_catalogues_no_truncate',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0047_ai-derivatives-and-property-calendar.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'resolve_ai_runtime_capability_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; resolves the exact immutable runtime capability tuple.`,
  },
  {
    name: 'reject_ai_read_barrier_mutation_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; protects read-barrier generations from direct mutation.`,
  },
  {
    name: 'acquire_ai_read_delivery_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; acquires a generation-pinned delivery lease.`,
  },
  {
    name: 'assert_ai_read_delivery_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; rechecks a generation-pinned delivery lease.`,
  },
  {
    name: 'close_ai_read_barrier_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; atomically advances a read-barrier generation.`,
  },
  {
    name: 'consume_ai_review_event_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0060_ai-plane-source-epoch-zero.sql',
    reason: `${NO_TRIGGER_DSL}; consumes review-analysis events in contiguous order. Introduced in 0048; 0058/0059 churned its source-epoch guard and 0060 settled it at the domain's 0-based numbering, alongside the eleven CHECK constraints that shared the same off-by-one.`,
  },
  {
    name: 'settle_ai_review_analysis_outcome_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; settles one durable analysis outcome.`,
  },
  {
    name: 'advance_ai_aggregate_revision_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; advances the aggregate revision after outcome settlement.`,
  },
  {
    name: 'reject_ai_execution_control_head_mutation_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; protects execution-control heads from direct mutation.`,
  },
  {
    name: 'transition_ai_execution_control_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; serializes hierarchical control transitions and history.`,
  },
  {
    name: 'reject_ai_canary_authorization_mutation_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; protects canary authorization lifecycle rows.`,
  },
  {
    name: 'reject_ai_canary_authorization_head_mutation_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; protects canary authorization heads.`,
  },
  {
    name: 'issue_ai_canary_authorization_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0067_ai-model-luna-switch.sql',
    reason: `${NO_TRIGGER_DSL}; atomically issues the exact canary operation, attempt, permit, and unsigned claim. Introduced in 0048; re-emitted whenever a digest it pins moves, most recently in 0066 for the provider and synthetic-canary profile digests.`,
  },
  {
    name: 'terminalize_unconsumed_ai_canary_authorization_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; releases every pre-dispatch canary execution artifact atomically.`,
  },
  {
    name: 'revoke_ai_canary_authorization_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; revokes an exact issued canary generation by head CAS.`,
  },
  {
    name: 'reap_expired_ai_canary_authorizations_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; expires bounded canary authorizations under lock.`,
  },
  {
    name: 'resolve_ai_property_local_date_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; resolves a reviewed timestamp against immutable calendar authority.`,
  },
  {
    name: 'assert_ai_property_calendar_authority_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; verifies the live calendar authority against its test vectors.`,
  },
  {
    name: 'ai_governance_policies_immutable',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_governance_policies_no_truncate',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_runtime_capability_profiles_immutable',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_runtime_capability_profiles_no_truncate',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_provider_deployment_capabilities_immutable',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_provider_deployment_capabilities_no_truncate',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_read_barrier_heads_transition_guard',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_read_barrier_heads_no_truncate',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_execution_control_heads_transition_guard',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_canary_authorizations_transition_guard',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_canary_authorizations_no_truncate',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_canary_authorization_heads_transition_guard',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_canary_authorization_heads_no_truncate',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_property_local_midnight_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0049_ai-execution-admission.sql',
    reason: `${NO_TRIGGER_DSL}; resolves a validated property-local midnight through PostgreSQL tzdata.`,
  },
  {
    name: 'ai_property_quota_adoption_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0049_ai-execution-admission.sql',
    reason: `${NO_TRIGGER_DSL}; computes the extension-only timezone/profile quota adoption boundary.`,
  },
  {
    name: 'enforce_ai_admission_cost_reservation_binding_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0049_ai-execution-admission.sql',
    reason: `${NO_TRIGGER_DSL}; validates reservation identity against the permit and operation binding.`,
  },
  {
    name: 'ai_admission_cost_reservations_binding_guard',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0049_ai-execution-admission.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'consume_ai_admission_rate_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0049_ai-execution-admission.sql',
    reason: `${NO_TRIGGER_DSL}; atomically consumes a fixed-window admission rate slot.`,
  },
  {
    name: 'admit_ai_property_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0067_ai-model-luna-switch.sql',
    reason: `${NO_TRIGGER_DSL}; performs the serialized property admission transaction. Introduced in 0049; 0063 repaired two guards that denied every property (organization_capability is keyed by purpose, and property_policy rows exist only where a suspension was recorded); 0064 swapped the reply token/draft expiries so token <= draft holds as both the gateway and the signed grant contract require.`,
  },
  {
    name: 'admit_ai_canary_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0049_ai-execution-admission.sql',
    reason: `${NO_TRIGGER_DSL}; performs the serialized canary admission transaction.`,
  },
  {
    name: 'settle_ai_execution_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0067_ai-model-luna-switch.sql',
    reason: `${NO_TRIGGER_DSL}; atomically settles permits, usage, cost, and canary state.`,
  },
  {
    name: 'reap_expired_ai_execution_permits_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0049_ai-execution-admission.sql',
    reason: `${NO_TRIGGER_DSL}; classifies expired consumed permits with SKIP LOCKED.`,
  },
  {
    name: 'google_execution_permit_revision_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0079_google-admission-database-authority.sql',
    reason: `${NO_TRIGGER_DSL}; derives the content-free completion fence used only by the Google admission database API.`,
  },
  {
    name: 'load_google_execution_permit_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0079_google-admission-database-authority.sql',
    reason: `${NO_TRIGGER_DSL}; exposes one permit snapshot to the execute-only Google admission role without table read privileges.`,
  },
  {
    name: 'start_google_execution_permit_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0124_google_organization_ownership.sql',
    reason: `${NO_TRIGGER_DSL}; locks, revalidates Organization-owned Google authority plus human/system generations, and starts or fences one permit atomically.`,
  },
  {
    name: 'start_google_execution_permit_v2',
    kind: 'function',
    owner: 'integration',
    source: 'drizzle/0162_google_oauth_gateway_admission.sql',
    reason: `${NO_TRIGGER_DSL}; adds exact prospective/existing OAuth exchange admission bound to the canonical Organization credential home and delegates every other route to v1.`,
  },
  {
    name: 'start_google_execution_permit_v3',
    kind: 'function',
    owner: 'integration',
    source: 'drizzle/0164_google_provider_recovery_authority.sql',
    reason: `${NO_TRIGGER_DSL}; admits only a disconnect revoke linked to its exact durable cleanup attempt and delegates every other provider route to v2.`,
  },
  {
    name: 'fail_google_execution_permit_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0079_google-admission-database-authority.sql',
    reason: `${NO_TRIGGER_DSL}; generation-fenced cleanup transition for a started Google permit whose grant cannot be issued.`,
  },
  {
    name: 'complete_google_execution_permit_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0079_google-admission-database-authority.sql',
    reason: `${NO_TRIGGER_DSL}; revision-fenced, code-only completion transition for a started Google permit.`,
  },
  {
    name: 'increment_reply_state_revision',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0051_puzzling_karma.sql',
    reason: `${NO_TRIGGER_DSL}; synchronizes overlap authorship and advances row/head revisions for material transitions.`,
  },
  {
    name: 'replies_increment_state_revision',
    kind: 'trigger',
    owner: 'review',
    source: 'drizzle/0051_puzzling_karma.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'advance_review_reply_state_revision_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0051_puzzling_karma.sql',
    reason: `${NO_TRIGGER_DSL}; atomically advances the Review-owned monotonic reply state head.`,
  },
  {
    name: 'protect_review_reply_state_revision_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0051_puzzling_karma.sql',
    reason: `${NO_TRIGGER_DSL}; rejects direct or non-contiguous reply-state head changes.`,
  },
  {
    name: 'reviews_protect_reply_state_revision',
    kind: 'trigger',
    owner: 'review',
    source: 'drizzle/0051_puzzling_karma.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'advance_review_reply_state_revision_on_delete_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0051_puzzling_karma.sql',
    reason: `${NO_TRIGGER_DSL}; preserves the Review reply-state head across internal Reply deletion.`,
  },
  {
    name: 'replies_advance_state_revision_on_delete',
    kind: 'trigger',
    owner: 'review',
    source: 'drizzle/0051_puzzling_karma.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'invalidate_ai_reply_adoption_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0052_misty_tana_nile.sql',
    reason: `${NO_TRIGGER_DSL}; invalidates content-free adoption receipts when an AI-assisted draft changes or is deleted.`,
  },
  {
    name: 'replies_invalidate_ai_adoption',
    kind: 'trigger',
    owner: 'review',
    source: 'drizzle/0052_misty_tana_nile.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'assert_current_ai_draft_binding_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0163_ai_reply_brand_profile_grounding.sql',
    reason: `${NO_TRIGGER_DSL}; validates legacy, personalized, and public Brand Profile-grounded AI reply drafts against current source and authorization state.`,
  },
  {
    name: 'purge_ai_reply_drafts_for_review_change_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0053_assert_ai_reply_binding.sql',
    reason: `${NO_TRIGGER_DSL}; purges stale AI reply drafts after source or analysis changes.`,
  },
  {
    name: 'reviews_purge_ai_reply_drafts',
    kind: 'trigger',
    owner: 'review',
    source: 'drizzle/0053_assert_ai_reply_binding.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'purge_ai_reply_drafts_for_property_change_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0053_assert_ai_reply_binding.sql',
    reason: `${NO_TRIGGER_DSL}; purges stale AI reply drafts after Property authorization changes.`,
  },
  {
    name: 'properties_purge_ai_reply_drafts',
    kind: 'trigger',
    owner: 'review',
    source: 'drizzle/0053_assert_ai_reply_binding.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'purge_ai_reply_drafts_for_profile_change_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0053_assert_ai_reply_binding.sql',
    reason: `${NO_TRIGGER_DSL}; purges stale AI reply drafts after processing-profile changes.`,
  },
  {
    name: 'ai_property_profiles_purge_ai_reply_drafts',
    kind: 'trigger',
    owner: 'review',
    source: 'drizzle/0053_assert_ai_reply_binding.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'purge_ai_reply_drafts_for_authorization_change_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0053_assert_ai_reply_binding.sql',
    reason: `${NO_TRIGGER_DSL}; purges stale AI reply drafts after merchant authorization changes.`,
  },
  {
    name: 'merchant_ai_enablement_purge_ai_reply_drafts',
    kind: 'trigger',
    owner: 'review',
    source: 'drizzle/0053_assert_ai_reply_binding.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'purge_ai_reply_drafts_for_control_change_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0053_assert_ai_reply_binding.sql',
    reason: `${NO_TRIGGER_DSL}; purges stale AI reply drafts after execution-control changes.`,
  },
  {
    name: 'ai_execution_controls_purge_ai_reply_drafts',
    kind: 'trigger',
    owner: 'review',
    source: 'drizzle/0053_assert_ai_reply_binding.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'retire_guest_contact_on_response_terminal_v1',
    kind: 'function',
    owner: 'guest',
    source: 'drizzle/0121_guest_contact_request_corrections.sql',
    reason: `${NO_TRIGGER_DSL}; atomically purges separately encrypted Contact Request material when private feedback is withdrawn or its Guest Response becomes terminal.`,
  },
  {
    name: 'guest_responses_retire_contact_request',
    kind: 'trigger',
    owner: 'guest',
    source: 'drizzle/0121_guest_contact_request_corrections.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'guard_operational_action_history_record_mutation_v1',
    kind: 'function',
    owner: 'activity',
    source: 'drizzle/0149_operational_action_history.sql',
    reason: `${NO_TRIGGER_DSL}; rejects core rewrites/deletion while permitting only one-way, legal-hold-aware identifier redaction.`,
  },
  {
    name: 'operational_action_history_records_mutation_guard',
    kind: 'trigger',
    owner: 'activity',
    source: 'drizzle/0149_operational_action_history.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'operational_action_history_records_truncate_guard',
    kind: 'trigger',
    owner: 'activity',
    source: 'drizzle/0149_operational_action_history.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'guard_operational_action_history_hold_mutation_v1',
    kind: 'function',
    owner: 'activity',
    source: 'drizzle/0149_operational_action_history.sql',
    reason: `${NO_TRIGGER_DSL}; retains legal-hold evidence and permits only its one-time explicit release transition.`,
  },
  {
    name: 'operational_action_history_legal_holds_mutation_guard',
    kind: 'trigger',
    owner: 'activity',
    source: 'drizzle/0149_operational_action_history.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'operational_action_history_legal_holds_truncate_guard',
    kind: 'trigger',
    owner: 'activity',
    source: 'drizzle/0149_operational_action_history.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'guard_operational_action_history_head_mutation_v1',
    kind: 'function',
    owner: 'activity',
    source: 'drizzle/0149_operational_action_history.sql',
    reason: `${NO_TRIGGER_DSL}; preserves monotonic one-at-a-time tenant sequence advancement and rejects deletion/truncation of the readiness head.`,
  },
  {
    name: 'operational_action_history_heads_update_guard',
    kind: 'trigger',
    owner: 'activity',
    source: 'drizzle/0149_operational_action_history.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'operational_action_history_heads_truncate_guard',
    kind: 'trigger',
    owner: 'activity',
    source: 'drizzle/0149_operational_action_history.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'guard_review_lifecycle_recovery_execution_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0150_review_lifecycle_recovery_execution.sql',
    reason: `${NO_TRIGGER_DSL}; preserves the exact signed target/policy/report binding and permits only bounded apply progress followed by exact recovery completion.`,
  },
  {
    name: 'review_lifecycle_recovery_executions_mutation_guard',
    kind: 'trigger',
    owner: 'review',
    source: 'drizzle/0150_review_lifecycle_recovery_execution.sql',
    reason: `${NO_TRIGGER_DSL}; rejects retargeting, replay-state reversal, deletion, and post-completion mutation of the one-shot receipt.`,
  },
  {
    name: 'review_lifecycle_recovery_executions_truncate_guard',
    kind: 'trigger',
    owner: 'review',
    source: 'drizzle/0150_review_lifecycle_recovery_execution.sql',
    reason: `${NO_TRIGGER_DSL}; keeps content-free recovery authority evidence durable across direct database access.`,
  },
]
