// Register of intentional DB-only constructs (BQC-5.4).
//
// The migration SQL track is the schema authority (see ../CONTEXT.md). Most
// constructs are ALSO declared in the Drizzle model so the semantic drift
// test (../schema-drift.ts) can verify them against pg_catalog. The objects
// listed here are the ones the Drizzle model deliberately does NOT own —
// either because drizzle-orm 0.45 has no DSL for them (CREATE FUNCTION /
// CREATE TRIGGER) or because they sit on Better Auth–owned tables where two
// migrators must not share DDL ownership.
//
// Rules (enforced both directions by the drift test):
//   - every entry here is verified to EXIST in pg_catalog;
//   - every trigger/function found in pg_catalog must appear here;
//   - entries here are exempt from model-vs-catalog comparison.
//
// To add one: append an entry with an explicit owner + reason, land it via a
// journaled migration (or a registered deploy sidecar applied after
// `pnpm db:migrate`), and keep the entry in sync if the object is dropped.

export type DbOnlyConstructKind =
  | 'trigger'
  | 'function'
  | 'index'
  | 'expression-index'
  | 'partial-index'
  | 'check'
  | 'enum'
  | 'index-direction'
  | 'other'

export type DbOnlyConstruct = Readonly<{
  /** Exact object name as it appears in pg_catalog. */
  name: string
  kind: DbOnlyConstructKind
  /** Owning context (or 'identity' / 'shared'). */
  owner: string
  /** Migration or sidecar path that creates the object. */
  source: string
  /** Why the Drizzle model does not own this construct. */
  reason: string
}>

const DAC_TRIGGERS_SIDECAR =
  'scripts/migrations/2026-07-06-permission-version-triggers.sql'
const NO_TRIGGER_DSL = 'drizzle-orm 0.45 has no CREATE FUNCTION/TRIGGER DSL'

export const DB_ONLY_CONSTRUCTS: readonly DbOnlyConstruct[] = [
  {
    name: 'organization_role_org_role_lower_unique',
    kind: 'expression-index',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason:
      'Unique index on Better Auth–owned "organizationRole" (organizationId, lower(role)); ' +
      'two migrators cannot share DDL ownership and drizzle-kit must not manage BA tables.',
  },
  {
    name: 'bump_permission_version',
    kind: 'function',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: `${NO_TRIGGER_DSL}; upsert helper for the permission_version counter.`,
  },
  {
    name: 'tgr_bump_perm_ba',
    kind: 'function',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: `${NO_TRIGGER_DSL}; AFTER-row trigger fn for BA-owned tables (camelCase "organizationId").`,
  },
  {
    name: 'tgr_bump_perm_app',
    kind: 'function',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: `${NO_TRIGGER_DSL}; AFTER-row trigger fn for app-owned tables (snake_case organization_id).`,
  },
  {
    name: 'guard_last_owner',
    kind: 'function',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: `${NO_TRIGGER_DSL}; last-owner backstop for direct-DB writes to member.`,
  },
  {
    name: 'member_perm_ver_ins',
    kind: 'trigger',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'member_perm_ver_del',
    kind: 'trigger',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'member_perm_ver_upd',
    kind: 'trigger',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'organization_role_perm_ver_iud',
    kind: 'trigger',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'organization_role_policy_perm_ver_iud',
    kind: 'trigger',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'staff_assignments_perm_ver_iud',
    kind: 'trigger',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'member_last_owner_del',
    kind: 'trigger',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'member_last_owner_upd',
    kind: 'trigger',
    owner: 'identity',
    source: DAC_TRIGGERS_SIDECAR,
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'tm_no_overlapping_participation_intervals',
    kind: 'index',
    owner: 'team',
    source: 'drizzle/0020_people-team-expansion.sql',
    reason:
      'Backing index for an EXCLUDE USING gist constraint; Drizzle has no exclusion-constraint DSL.',
  },
  {
    name: 'pr_no_overlapping_responsibility_intervals',
    kind: 'index',
    owner: 'staff',
    source: 'drizzle/0020_people-team-expansion.sql',
    reason:
      'Backing index for an EXCLUDE USING gist constraint; Drizzle has no exclusion-constraint DSL.',
  },
  {
    name: 'tpgs_no_overlapping_scope_intervals',
    kind: 'index',
    owner: 'team',
    source: 'drizzle/0020_people-team-expansion.sql',
    reason:
      'Backing index for an EXCLUDE USING gist constraint; Drizzle has no exclusion-constraint DSL.',
  },
  {
    name: 'pgm_no_overlapping_portal_intervals',
    kind: 'index',
    owner: 'portal',
    source: 'drizzle/0020_people-team-expansion.sql',
    reason:
      'Backing index for an EXCLUDE USING gist constraint; Drizzle has no exclusion-constraint DSL.',
  },
  {
    name: 'reject_goal_immutable_update',
    kind: 'function',
    owner: 'goal',
    source: 'drizzle/0024_goal-versioning.sql',
    reason: `${NO_TRIGGER_DSL}; rejects updates and deletes on governed goal facts.`,
  },
  {
    name: 'goal_definition_versions_immutable',
    kind: 'trigger',
    owner: 'goal',
    source: 'drizzle/0024_goal-versioning.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'goal_evaluations_immutable',
    kind: 'trigger',
    owner: 'goal',
    source: 'drizzle/0024_goal-versioning.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'reject_recognition_immutable_mutation',
    kind: 'function',
    owner: 'recognition',
    source: 'drizzle/0025_recognition-governance.sql',
    reason: `${NO_TRIGGER_DSL}; rejects updates and deletes on governed recognition facts.`,
  },
  {
    name: 'recognition_board_snapshots_append_only',
    kind: 'trigger',
    owner: 'recognition',
    source: 'drizzle/0025_recognition-governance.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'recognition_board_entries_append_only',
    kind: 'trigger',
    owner: 'recognition',
    source: 'drizzle/0025_recognition-governance.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'recognition_reconciliation_events_append_only',
    kind: 'trigger',
    owner: 'recognition',
    source: 'drizzle/0025_recognition-governance.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'badge_definition_versions_append_only',
    kind: 'trigger',
    owner: 'recognition',
    source: 'drizzle/0025_recognition-governance.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'recognition_awards_append_only',
    kind: 'trigger',
    owner: 'recognition',
    source: 'drizzle/0025_recognition-governance.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'recognition_award_status_facts_append_only',
    kind: 'trigger',
    owner: 'recognition',
    source: 'drizzle/0025_recognition-governance.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'reject_capability_compliance_approval_mutation',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0029_google-content-control.sql',
    reason: `${NO_TRIGGER_DSL}; rejects in-place mutation of signed approval bindings.`,
  },
  {
    name: 'capability_compliance_approvals_append_only',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0029_google-content-control.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_epoch_millis_v1',
    kind: 'function',
    owner: 'shared',
    source: 'drizzle/0043_review-source-provenance.sql',
    reason: `${NO_TRIGGER_DSL}; exact PostgreSQL epoch-millisecond conversion used by AI source authorization.`,
  },
  {
    name: 'ai_advisory_lock_key_v1',
    kind: 'function',
    owner: 'shared',
    source: 'drizzle/0043_review-source-provenance.sql',
    reason: `${NO_TRIGGER_DSL}; domain-separated advisory-lock key derivation for AI and provider workflows.`,
  },
  {
    name: 'lock_review_ai_analysis_head_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0043_review-source-provenance.sql',
    reason: `${NO_TRIGGER_DSL}; atomically validates the source epoch and allocates a review analysis sequence.`,
  },
  {
    name: 'reposition_merchant_ai_analysis_watermark_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0074_ai-backfill-consent-lineage.sql',
    reason: `${NO_TRIGGER_DSL}; repositions the merchant review-analysis watermark and bumps the analysis epoch in one transaction, so an audited backfill cannot leave the watermark and the epoch disagreeing, and derives the consent-evidence actor from the latest merchant consent decision in the lineage — never from another analysis_backfill row — so the ledger names an accountable member rather than the operator.`,
  },
  {
    name: 'initialize_review_provider_subject_hmac_key_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0043_review-source-provenance.sql',
    reason: `${NO_TRIGGER_DSL}; initializes the provider-subject HMAC key inventory under an advisory lock.`,
  },
  {
    name: 'review_provider_subject_hmac_key_inventory_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0043_review-source-provenance.sql',
    reason: `${NO_TRIGGER_DSL}; exposes only the content-free provider-subject key inventory.`,
  },
  {
    name: 'trust_next_review_provider_subject_hmac_key_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0043_review-source-provenance.sql',
    reason: `${NO_TRIGGER_DSL}; stages one trusted-next provider-subject key under a generation fence.`,
  },
  {
    name: 'rotate_review_provider_subject_hmac_key_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0043_review-source-provenance.sql',
    reason: `${NO_TRIGGER_DSL}; atomically promotes trusted-next and retires the prior provider-subject key.`,
  },
  {
    name: 'remove_review_provider_subject_hmac_key_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0043_review-source-provenance.sql',
    reason: `${NO_TRIGGER_DSL}; removes a retired key only after no provider-subject mapping references it.`,
  },
  {
    name: 'assert_ai_capability_set_executable_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0044_merchant-ai-authorization.sql',
    reason: `${NO_TRIGGER_DSL}; fail-closed merchant AI capability-to-runtime catalogue validation.`,
  },
  {
    name: 'guard_merchant_ai_evidence_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0044_merchant-ai-authorization.sql',
    reason: `${NO_TRIGGER_DSL}; append-only consent-evidence transition guard.`,
  },
  {
    name: 'merchant_ai_consent_evidence_append_guard',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0044_merchant-ai-authorization.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'merchant_ai_consent_evidence_truncate_guard',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0044_merchant-ai-authorization.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'guard_merchant_ai_enablement_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0044_merchant-ai-authorization.sql',
    reason: `${NO_TRIGGER_DSL}; validates the mutable authorization head against immutable evidence.`,
  },
  {
    name: 'merchant_ai_enablement_transition_guard',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0044_merchant-ai-authorization.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'merchant_ai_enablement_truncate_guard',
    kind: 'trigger',
    owner: 'identity',
    source: 'drizzle/0044_merchant-ai-authorization.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'apply_merchant_ai_transition_v1',
    kind: 'function',
    owner: 'identity',
    source: 'drizzle/0060_ai-plane-source-epoch-zero.sql',
    reason: `${NO_TRIGGER_DSL}; serializes merchant AI authorization, source epoch, and analysis watermark transitions. Introduced in 0045; 0060 relaxed its authorized-source-epoch guard to the domain's 0-based numbering.`,
  },
  {
    name: 'assert_ai_runtime_catalogue_ready_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0078_ai-language-catalogue-repin.sql',
    reason: `${NO_TRIGGER_DSL}; verifies the complete immutable runtime catalogue at readiness. Introduced in 0046; re-emitted whenever the catalogue projection it byte-compares moves, most recently in 0078 for the shared reply-language catalogue extraction.`,
  },
  {
    name: 'reject_ai_catalogue_mutation_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: `${NO_TRIGGER_DSL}; rejects mutation of immutable AI catalogues and control history.`,
  },
  {
    name: 'ai_property_local_date_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0047_ai-derivatives-and-property-calendar.sql',
    reason: `${NO_TRIGGER_DSL}; sole versioned reviewed-at to property-local-date conversion.`,
  },
  {
    name: 'ai_provider_profiles_immutable',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_provider_profiles_no_truncate',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_routing_policies_immutable',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_routing_policies_no_truncate',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_operation_profiles_immutable',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_operation_profiles_no_truncate',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_control_history_immutable',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_control_history_no_truncate',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_property_calendar_catalogues_immutable',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0047_ai-derivatives-and-property-calendar.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_property_calendar_catalogues_no_truncate',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0047_ai-derivatives-and-property-calendar.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'resolve_ai_runtime_capability_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; resolves the exact immutable runtime capability tuple.`,
  },
  {
    name: 'reject_ai_read_barrier_mutation_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; protects read-barrier generations from direct mutation.`,
  },
  {
    name: 'acquire_ai_read_delivery_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; acquires a generation-pinned delivery lease.`,
  },
  {
    name: 'assert_ai_read_delivery_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; rechecks a generation-pinned delivery lease.`,
  },
  {
    name: 'close_ai_read_barrier_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; atomically advances a read-barrier generation.`,
  },
  {
    name: 'consume_ai_review_event_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0060_ai-plane-source-epoch-zero.sql',
    reason: `${NO_TRIGGER_DSL}; consumes review-analysis events in contiguous order. Introduced in 0048; 0058/0059 churned its source-epoch guard and 0060 settled it at the domain's 0-based numbering, alongside the eleven CHECK constraints that shared the same off-by-one.`,
  },
  {
    name: 'settle_ai_review_analysis_outcome_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; settles one durable analysis outcome.`,
  },
  {
    name: 'advance_ai_aggregate_revision_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; advances the aggregate revision after outcome settlement.`,
  },
  {
    name: 'reject_ai_execution_control_head_mutation_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; protects execution-control heads from direct mutation.`,
  },
  {
    name: 'transition_ai_execution_control_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; serializes hierarchical control transitions and history.`,
  },
  {
    name: 'reject_ai_canary_authorization_mutation_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; protects canary authorization lifecycle rows.`,
  },
  {
    name: 'reject_ai_canary_authorization_head_mutation_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; protects canary authorization heads.`,
  },
  {
    name: 'issue_ai_canary_authorization_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0067_ai-model-luna-switch.sql',
    reason: `${NO_TRIGGER_DSL}; atomically issues the exact canary operation, attempt, permit, and unsigned claim. Introduced in 0048; re-emitted whenever a digest it pins moves, most recently in 0066 for the provider and synthetic-canary profile digests.`,
  },
  {
    name: 'terminalize_unconsumed_ai_canary_authorization_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; releases every pre-dispatch canary execution artifact atomically.`,
  },
  {
    name: 'revoke_ai_canary_authorization_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; revokes an exact issued canary generation by head CAS.`,
  },
  {
    name: 'reap_expired_ai_canary_authorizations_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; expires bounded canary authorizations under lock.`,
  },
  {
    name: 'resolve_ai_property_local_date_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; resolves a reviewed timestamp against immutable calendar authority.`,
  },
  {
    name: 'assert_ai_property_calendar_authority_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: `${NO_TRIGGER_DSL}; verifies the live calendar authority against its test vectors.`,
  },
  {
    name: 'ai_governance_policies_immutable',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_governance_policies_no_truncate',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_runtime_capability_profiles_immutable',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_runtime_capability_profiles_no_truncate',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_provider_deployment_capabilities_immutable',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_provider_deployment_capabilities_no_truncate',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0046_ai-control-plane-and-operations.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_read_barrier_heads_transition_guard',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_read_barrier_heads_no_truncate',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_execution_control_heads_transition_guard',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_canary_authorizations_transition_guard',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_canary_authorizations_no_truncate',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_canary_authorization_heads_transition_guard',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_canary_authorization_heads_no_truncate',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0048_ai-lifecycle-authority.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'ai_property_local_midnight_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0049_ai-execution-admission.sql',
    reason: `${NO_TRIGGER_DSL}; resolves a validated property-local midnight through PostgreSQL tzdata.`,
  },
  {
    name: 'ai_property_quota_adoption_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0049_ai-execution-admission.sql',
    reason: `${NO_TRIGGER_DSL}; computes the extension-only timezone/profile quota adoption boundary.`,
  },
  {
    name: 'enforce_ai_admission_cost_reservation_binding_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0049_ai-execution-admission.sql',
    reason: `${NO_TRIGGER_DSL}; validates reservation identity against the permit and operation binding.`,
  },
  {
    name: 'ai_admission_cost_reservations_binding_guard',
    kind: 'trigger',
    owner: 'ai',
    source: 'drizzle/0049_ai-execution-admission.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'consume_ai_admission_rate_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0049_ai-execution-admission.sql',
    reason: `${NO_TRIGGER_DSL}; atomically consumes a fixed-window admission rate slot.`,
  },
  {
    name: 'admit_ai_property_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0067_ai-model-luna-switch.sql',
    reason: `${NO_TRIGGER_DSL}; performs the serialized property admission transaction. Introduced in 0049; 0063 repaired two guards that denied every property (organization_capability is keyed by purpose, and property_policy rows exist only where a suspension was recorded); 0064 swapped the reply token/draft expiries so token <= draft holds as both the gateway and the signed grant contract require.`,
  },
  {
    name: 'admit_ai_canary_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0049_ai-execution-admission.sql',
    reason: `${NO_TRIGGER_DSL}; performs the serialized canary admission transaction.`,
  },
  {
    name: 'settle_ai_execution_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0067_ai-model-luna-switch.sql',
    reason: `${NO_TRIGGER_DSL}; atomically settles permits, usage, cost, and canary state.`,
  },
  {
    name: 'reap_expired_ai_execution_permits_v1',
    kind: 'function',
    owner: 'ai',
    source: 'drizzle/0049_ai-execution-admission.sql',
    reason: `${NO_TRIGGER_DSL}; classifies expired consumed permits with SKIP LOCKED.`,
  },
  {
    name: 'increment_reply_state_revision',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0051_puzzling_karma.sql',
    reason: `${NO_TRIGGER_DSL}; synchronizes overlap authorship and advances row/head revisions for material transitions.`,
  },
  {
    name: 'replies_increment_state_revision',
    kind: 'trigger',
    owner: 'review',
    source: 'drizzle/0051_puzzling_karma.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'advance_review_reply_state_revision_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0051_puzzling_karma.sql',
    reason: `${NO_TRIGGER_DSL}; atomically advances the Review-owned monotonic reply state head.`,
  },
  {
    name: 'protect_review_reply_state_revision_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0051_puzzling_karma.sql',
    reason: `${NO_TRIGGER_DSL}; rejects direct or non-contiguous reply-state head changes.`,
  },
  {
    name: 'reviews_protect_reply_state_revision',
    kind: 'trigger',
    owner: 'review',
    source: 'drizzle/0051_puzzling_karma.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'advance_review_reply_state_revision_on_delete_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0051_puzzling_karma.sql',
    reason: `${NO_TRIGGER_DSL}; preserves the Review reply-state head across internal Reply deletion.`,
  },
  {
    name: 'replies_advance_state_revision_on_delete',
    kind: 'trigger',
    owner: 'review',
    source: 'drizzle/0051_puzzling_karma.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'invalidate_ai_reply_adoption_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0052_misty_tana_nile.sql',
    reason: `${NO_TRIGGER_DSL}; invalidates content-free adoption receipts when an AI-assisted draft changes or is deleted.`,
  },
  {
    name: 'replies_invalidate_ai_adoption',
    kind: 'trigger',
    owner: 'review',
    source: 'drizzle/0052_misty_tana_nile.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'assert_current_ai_draft_binding_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0053_assert_ai_reply_binding.sql',
    reason: `${NO_TRIGGER_DSL}; validates a persisted AI reply draft against current source and authorization state.`,
  },
  {
    name: 'purge_ai_reply_drafts_for_review_change_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0053_assert_ai_reply_binding.sql',
    reason: `${NO_TRIGGER_DSL}; purges stale AI reply drafts after source or analysis changes.`,
  },
  {
    name: 'reviews_purge_ai_reply_drafts',
    kind: 'trigger',
    owner: 'review',
    source: 'drizzle/0053_assert_ai_reply_binding.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'purge_ai_reply_drafts_for_property_change_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0053_assert_ai_reply_binding.sql',
    reason: `${NO_TRIGGER_DSL}; purges stale AI reply drafts after Property authorization changes.`,
  },
  {
    name: 'properties_purge_ai_reply_drafts',
    kind: 'trigger',
    owner: 'review',
    source: 'drizzle/0053_assert_ai_reply_binding.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'purge_ai_reply_drafts_for_profile_change_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0053_assert_ai_reply_binding.sql',
    reason: `${NO_TRIGGER_DSL}; purges stale AI reply drafts after processing-profile changes.`,
  },
  {
    name: 'ai_property_profiles_purge_ai_reply_drafts',
    kind: 'trigger',
    owner: 'review',
    source: 'drizzle/0053_assert_ai_reply_binding.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'purge_ai_reply_drafts_for_authorization_change_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0053_assert_ai_reply_binding.sql',
    reason: `${NO_TRIGGER_DSL}; purges stale AI reply drafts after merchant authorization changes.`,
  },
  {
    name: 'merchant_ai_enablement_purge_ai_reply_drafts',
    kind: 'trigger',
    owner: 'review',
    source: 'drizzle/0053_assert_ai_reply_binding.sql',
    reason: NO_TRIGGER_DSL,
  },
  {
    name: 'purge_ai_reply_drafts_for_control_change_v1',
    kind: 'function',
    owner: 'review',
    source: 'drizzle/0053_assert_ai_reply_binding.sql',
    reason: `${NO_TRIGGER_DSL}; purges stale AI reply drafts after execution-control changes.`,
  },
  {
    name: 'ai_execution_controls_purge_ai_reply_drafts',
    kind: 'trigger',
    owner: 'review',
    source: 'drizzle/0053_assert_ai_reply_binding.sql',
    reason: NO_TRIGGER_DSL,
  },
]
