// Schema barrel — import all schema files here
// so Drizzle kit and the DB connection can reference a single entry point.

export * from './ai.schema'
export * from './auth'
export * from './dac.schema'
export * from './audit'
export * from './property.schema'
export * from './property-operation-receipt.schema'
export * from './people-access.schema'
export * from './portal.schema'
export * from './portal-group.schema'
export * from './guest.schema'
export * from './google-connection.schema'
export * from './google-import-discovery.schema'
export * from './google-import-v2.schema'
export * from './review.schema'
export * from './review-sync.schema'
export * from './inbox.schema'
export * from './identity-governance.schema'
export * from './organization-lifecycle.schema'
export * from './context-organization-lifecycle-receipts.schema'
export * from './backup-erasure-ledger.schema'
export * from './property-erase.schema'
export * from './privacy-request.schema'
export * from './beta-feedback-triage.schema'
export * from './invited-registration.schema'
export * from './metric.schema'
export * from './goal.schema'
export * from './activity.schema'
export * from './notification.schema'
export * from './outbox.schema'
export * from './policy.schema'
export * from './merchant-ai-authorization.schema'
export * from './google-content-control.schema'
export * from './recovery.schema'
export * from './dashboard.schema'
