// Schema barrel — import all schema files here
// so Drizzle kit and the DB connection can reference a single entry point.

export * from './auth'
export * from './dac.schema'
export * from './audit'
export * from './property.schema'
export * from './team.schema'
export * from './staff-assignment.schema'
export * from './portal.schema'
export * from './portal-group.schema'
export * from './guest.schema'
export * from './google-connection.schema'
export * from './gbp-cache.schema'
export * from './gbp-import-job.schema'
export * from './review.schema'
export * from './inbox.schema'
export * from './badge.schema'
export * from './leaderboard.schema'
export * from './metric.schema'
export * from './goal.schema'
export * from './activity.schema'
export * from './notification.schema'
