import { readdir, readFile, writeFile } from 'node:fs/promises'

const adrDir = new URL('../docs/adr/', import.meta.url)
const files = (await readdir(adrDir))
  .filter((file) => /^\d{4}-.+\.md$/u.test(file))
  .sort()

const records = await Promise.all(
  files.map(async (file) => {
    const source = await readFile(new URL(file, adrDir), 'utf8')
    const frontmatter = source.match(/^---\n([\s\S]*?)\n---/u)?.[1]
    const title = source.match(/^# \d{4} [—:-] (.+)$/mu)?.[1]
    if (!frontmatter || !title) throw new Error(`Invalid ADR metadata: ${file}`)
    const metadata = Object.fromEntries(
      frontmatter.split('\n').map((line) => {
        const separator = line.indexOf(':')
        return [line.slice(0, separator), line.slice(separator + 1).trim()]
      }),
    )
    return { file, number: file.slice(0, 4), title, ...metadata }
  }),
)

const present = new Set(records.map(({ number }) => Number(number)))
const missing = []
for (let number = 1; number < Number(records.at(-1)?.number ?? 0); number++) {
  if (!present.has(number)) missing.push(number)
}
const ranges = []
for (const number of missing) {
  const previous = ranges.at(-1)
  if (previous?.[1] === number - 1) previous[1] = number
  else ranges.push([number, number])
}
const format = (number) => String(number).padStart(4, '0')
const gaps = ranges
  .map(([start, end]) =>
    start === end ? format(start) : `${format(start)}–${format(end)}`,
  )
  .map((range) => `\`${range}\``)
  .join(', ')

const headers = ['ADR', 'Decision', 'Status', 'Superseded by']
const rows = records.map(
  ({ file, number, title, status, superseded_by: supersededBy }) => [
    `[${number}](${file})`,
    title,
    status,
    supersededBy ?? '—',
  ],
)
const widths = headers.map((header, index) =>
  Math.max(header.length, ...rows.map((row) => row[index].length)),
)
const renderRow = (cells, separator = false) =>
  `| ${cells
    .map((cell, index) =>
      separator ? '-'.repeat(widths[index]) : cell.padEnd(widths[index]),
    )
    .join(' | ')} |`
const table = [
  renderRow(headers),
  renderRow(headers, true),
  ...rows.map((row) => renderRow(row)),
].join('\n')
const output = `# Architecture Decision Record index

Generated by \`node scripts/adr-index.mjs\` from retained ADR frontmatter.
Missing numbers are retired, merged, or never issued: ${gaps}. Numbers are never reused.

${table}
`

await writeFile(new URL('README.md', adrDir), output)
