import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import process from 'node:process'
import { Converter as createCn2tConverter } from 'opencc-js/cn2t'
import { Converter as createT2cnConverter } from 'opencc-js/t2cn'
import { canonicalizeRfc8785 } from '../src/shared/merchant-ai-notice-contract'
import { computeAiLanguageProfileDigest } from './ai-language-attestation'
import { format, resolveConfig } from 'prettier'

const ROOT = resolve(import.meta.dirname, '..')
const PRETTIER_CONFIG = (await resolveConfig(resolve(ROOT, 'package.json'))) ?? {}
const OUTPUT = resolve(ROOT, 'src/shared/generated/ai-zh-orthography-v1.ts')
const MANIFEST_OUTPUT = resolve(
  ROOT,
  'src/shared/ai-zh-orthography-profile-v1.manifest.json',
)
const PACKAGE_ROOT = resolve(ROOT, 'node_modules/opencc-js')
const WRAPPER_PATH = 'src/shared/ai-zh-orthography-verifier.ts'
const VECTORS_PATH = 'src/shared/ai-zh-orthography-verifier-v1.vectors.json'
const PACKAGE_VERSION = '1.4.1'
const PACKAGE_INTEGRITY =
  'sha512-2lPLcrg7cnh1ATSduOxhnk/jq6KlR6w+5Ihl4wF7Z5e5Rva4vxTyugV5rZ7EiUCOZl+EDOLetIix+BhgYDCC+A=='
const UNICODE_VERSION = '17.0'
const ICU_VERSION = '78.2'
const MEMBERS = Object.freeze([
  [
    'dist/esm/cn2t.js',
    'bd8511eaf9fb88fb47b0ff52965d352658c2c389af2ac09912d0d6eb5acaf3ad',
  ],
  [
    'dist/esm/t2cn.js',
    '69fa82bbe93d05746ba5ab96e9c85864ca4f91c984d198abf85a098b43451a86',
  ],
] as const)

type EvidenceRow = readonly [codePoint: number, evidence: 1 | 2]

function sha256(bytes: Uint8Array | string): string {
  return createHash('sha256').update(bytes).digest('hex')
}

function assertInputs(): void {
  if (
    process.versions.unicode !== UNICODE_VERSION ||
    process.versions.icu !== ICU_VERSION
  ) {
    throw new Error(
      `Unicode runtime mismatch: ${process.versions.unicode}/${process.versions.icu}`,
    )
  }
  const packageJson = JSON.parse(
    readFileSync(resolve(PACKAGE_ROOT, 'package.json'), 'utf8'),
  ) as {
    version?: unknown
  }
  if (packageJson.version !== PACKAGE_VERSION)
    throw new Error('opencc-js version mismatch')
  for (const [path, expectedDigest] of MEMBERS) {
    const actualDigest = sha256(readFileSync(resolve(PACKAGE_ROOT, path)))
    if (actualDigest !== expectedDigest)
      throw new Error(`opencc-js member drift: ${path}`)
  }
}

function generateRows(): readonly EvidenceRow[] {
  const cn2t = createCn2tConverter({ from: 'cn', to: 't' })
  const t2cn = createT2cnConverter({ from: 't', to: 'cn' })
  const hanLetter = /^(?=\p{Letter}$)\p{Script_Extensions=Han}$/u
  const rows: EvidenceRow[] = []
  for (let codePoint = 0; codePoint <= 0x10ffff; codePoint += 1) {
    if (codePoint >= 0xd800 && codePoint <= 0xdfff) continue
    const scalar = String.fromCodePoint(codePoint)
    if (!hanLetter.test(scalar)) continue
    const simplified = t2cn(scalar)
    const traditional = cn2t(scalar)
    if (simplified === scalar && traditional !== scalar) rows.push([codePoint, 1])
    else if (traditional === scalar && simplified !== scalar) rows.push([codePoint, 2])
  }
  return Object.freeze(rows)
}

function render(rows: readonly EvidenceRow[]): { table: string; tableDigest: string } {
  const tableDigest = sha256(
    `repkey-ai-zh-orthography-table-v1\0${canonicalizeRfc8785(rows)}`,
  )
  const flat = rows.flatMap(([codePoint, evidence]) => [codePoint, evidence])
  const lines = Array.from({ length: Math.ceil(flat.length / 16) }, (_, index) =>
    flat
      .slice(index * 16, index * 16 + 16)
      .map((value) => `0x${value.toString(16)}`)
      .join(', '),
  )
    .map((line) => `  ${line},`)
    .join('\n')
  return {
    tableDigest,
    table:
      `// Generated by scripts/generate-ai-zh-orthography-table.ts. Do not edit.\n` +
      `export const AI_ZH_ORTHOGRAPHY_TABLE_DIGEST = '${tableDigest}' as const\n` +
      `export const AI_ZH_ORTHOGRAPHY_EVIDENCE_ROW_COUNT = ${rows.length} as const\n` +
      `export const AI_ZH_ORTHOGRAPHY_EVIDENCE = new Uint32Array([\n${lines}\n])\n`,
  }
}
assertInputs()
const rows = generateRows()
const rawRendered = render(rows)
const rendered = {
  ...rawRendered,
  table: await format(rawRendered.table, {
    ...PRETTIER_CONFIG,
    filepath: OUTPUT,
  }),
}
const generatorPath = 'scripts/generate-ai-zh-orthography-table.ts'
const generatorBytes = readFileSync(resolve(ROOT, generatorPath))
const wrapperBytes = readFileSync(resolve(ROOT, WRAPPER_PATH))
const vectorValue = JSON.parse(
  readFileSync(resolve(ROOT, VECTORS_PATH), 'utf8'),
) as unknown
const canonicalVectorBytes = Buffer.from(canonicalizeRfc8785(vectorValue), 'utf8')
const profileManifest = {
  version: 'zh-orthography-verifier-v1',
  unicodeVersion: `${UNICODE_VERSION}.0`,
  icuVersion: ICU_VERSION,
  package: { name: 'opencc-js', version: PACKAGE_VERSION, integrity: PACKAGE_INTEGRITY },
  importedMembers: MEMBERS.map(([path, memberSha256]) => ({
    path,
    sha256: memberSha256,
  })),
  generator: { path: generatorPath, sha256: sha256(generatorBytes) },
  table: {
    path: 'src/shared/generated/ai-zh-orthography-v1.ts',
    sha256: sha256(rendered.table),
    profileDigest: rendered.tableDigest,
  },
  vectors: {
    path: VECTORS_PATH,
    sha256: sha256(canonicalVectorBytes),
    cases: vectorValue,
  },
  constants: { minimumDecisiveLetters: 4, ratioNumerator: 4, ratioDenominator: 5 },
}
const profileBytes = Buffer.from(canonicalizeRfc8785(profileManifest), 'utf8')
const manifest = {
  ...profileManifest,
  wrapper: { path: WRAPPER_PATH, sha256: sha256(wrapperBytes) },
  attestationDigest: computeAiLanguageProfileDigest(
    'repkey-zh-orthography-verifier-profile-v1\0',
    [
      { path: WRAPPER_PATH, bytes: wrapperBytes },
      {
        path: 'src/shared/ai-zh-orthography-profile-v1.profile.json',
        bytes: profileBytes,
      },
    ],
  ),
}
const manifestText = await format(canonicalizeRfc8785(manifest), {
  ...PRETTIER_CONFIG,
  filepath: MANIFEST_OUTPUT,
})

if (process.argv.includes('--check')) {
  if (readFileSync(OUTPUT, 'utf8') !== rendered.table)
    throw new Error('Orthography table is stale')
  if (readFileSync(MANIFEST_OUTPUT, 'utf8') !== manifestText)
    throw new Error('Orthography manifest is stale')
  process.stdout.write('Chinese orthography generated artifacts are current\n')
} else {
  mkdirSync(dirname(OUTPUT), { recursive: true })
  writeFileSync(OUTPUT, rendered.table, 'utf8')
  writeFileSync(MANIFEST_OUTPUT, manifestText, 'utf8')
  process.stdout.write(`Generated ${OUTPUT} and ${MANIFEST_OUTPUT}\n`)
}
