import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import process from 'node:process'
import { canonicalizeRfc8785 } from '../src/shared/merchant-ai-notice-contract'
import { format, resolveConfig } from 'prettier'

const ROOT = process.cwd()
const PRETTIER_CONFIG = (await resolveConfig(resolve(ROOT, 'package.json'))) ?? {}
const OUTPUT = resolve(
  ROOT,
  'src/shared/generated/ai-review-language-canonical-regions-v1.ts',
)
const EXPECTED_NODE_VERSION = '22.23.2'
const EXPECTED_ICU_VERSION = '78.2'
const EXPECTED_UNICODE_VERSION = '17.0'
const ASCII_UPPER = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

if (
  process.versions.node !== EXPECTED_NODE_VERSION ||
  process.versions.icu !== EXPECTED_ICU_VERSION ||
  process.versions.unicode !== EXPECTED_UNICODE_VERSION
) {
  throw new Error(
    `Canonical-region generation requires Node ${EXPECTED_NODE_VERSION}, ICU ${EXPECTED_ICU_VERSION}, Unicode ${EXPECTED_UNICODE_VERSION}`,
  )
}

const displayNames = new Intl.DisplayNames(['en'], {
  type: 'region',
  fallback: 'none',
})

function isCanonicalKnownRegion(region: string): boolean {
  let locale: Intl.Locale
  try {
    locale = new Intl.Locale(`und-${region}`)
  } catch {
    return false
  }
  return (
    region !== 'ZZ' && locale.region === region && displayNames.of(region) !== undefined
  )
}

const regions: string[] = []
for (const first of ASCII_UPPER) {
  for (const second of ASCII_UPPER) {
    const region = `${first}${second}`
    if (isCanonicalKnownRegion(region)) regions.push(region)
  }
}
for (let value = 0; value <= 999; value += 1) {
  const region = value.toString().padStart(3, '0')
  if (isCanonicalKnownRegion(region)) regions.push(region)
}
regions.sort()

if (new Set(regions).size !== regions.length || regions.length === 0) {
  throw new Error('Canonical-region generation produced an invalid set')
}

const regionDigest = createHash('sha256')
  .update('repkey-ai-review-language-canonical-regions-v1\0', 'utf8')
  .update(canonicalizeRfc8785(regions), 'utf8')
  .digest('hex')

const unformattedOutput =
  `// Generated by scripts/generate-ai-review-language-regions.ts. Do not edit.\n` +
  `export const AI_REVIEW_LANGUAGE_REGION_NODE_VERSION = '${EXPECTED_NODE_VERSION}' as const\n` +
  `export const AI_REVIEW_LANGUAGE_REGION_ICU_VERSION = '${EXPECTED_ICU_VERSION}' as const\n` +
  `export const AI_REVIEW_LANGUAGE_REGION_UNICODE_VERSION = '${EXPECTED_UNICODE_VERSION}' as const\n` +
  `export const AI_REVIEW_LANGUAGE_CANONICAL_REGION_TABLE_DIGEST = '${regionDigest}' as const\n` +
  `export const AI_REVIEW_LANGUAGE_CANONICAL_REGIONS_V1 = Object.freeze(${JSON.stringify(regions)}) as readonly string[]\n\n` +
  `export function isCanonicalAiReviewLanguageRegion(value: string): boolean {\n` +
  `  let low = 0\n` +
  `  let high = AI_REVIEW_LANGUAGE_CANONICAL_REGIONS_V1.length - 1\n` +
  `  while (low <= high) {\n` +
  `    const middle = (low + high) >>> 1\n` +
  `    const candidate = AI_REVIEW_LANGUAGE_CANONICAL_REGIONS_V1[middle]!\n` +
  `    if (candidate === value) return true\n` +
  `    if (candidate < value) low = middle + 1\n` +
  `    else high = middle - 1\n` +
  `  }\n` +
  `  return false\n` +
  `}\n`
const output = await format(unformattedOutput, {
  ...PRETTIER_CONFIG,
  filepath: OUTPUT,
})

if (process.argv.includes('--check')) {
  if (readFileSync(OUTPUT, 'utf8') !== output) {
    throw new Error('Canonical AI review-language region table is stale')
  }
  process.stdout.write('Canonical AI review-language region table is current\n')
} else {
  writeFileSync(OUTPUT, output, 'utf8')
  process.stdout.write(`Generated ${OUTPUT} with ${regions.length} canonical regions\n`)
}
