import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import process from 'node:process'
import { canonicalizeRfc8785 } from '../src/shared/merchant-ai-notice-contract'
import { computeAiLanguageProfileDigest } from './ai-language-attestation'
import { format, resolveConfig } from 'prettier'

const ROOT = resolve(import.meta.dirname, '..')
const PRETTIER_CONFIG = (await resolveConfig(resolve(ROOT, 'package.json'))) ?? {}
const OUTPUT = resolve(ROOT, 'src/shared/generated/ai-language-script-extensions-v17.ts')
const MANIFEST_OUTPUT = resolve(
  ROOT,
  'src/shared/ai-language-script-consistency-v1.manifest.json',
)
const GENERATOR_PATH = 'scripts/generate-ai-language-script-table.ts'
const TABLE_PATH = 'src/shared/generated/ai-language-script-extensions-v17.ts'
const WRAPPER_PATH = 'src/shared/ai-language-script-consistency.ts'
const VECTORS_PATH = 'src/shared/ai-language-script-consistency-v1.vectors.json'
const EXPECTED_UNICODE_VERSION = '17.0'
const EXPECTED_ICU_VERSION = '78.2'

const SCRIPTS = [
  ['Latin', 1],
  ['Cyrillic', 2],
  ['Arabic', 4],
  ['Hebrew', 8],
  ['Devanagari', 16],
  ['Bengali', 32],
  ['Tamil', 64],
  ['Thai', 128],
  ['Han', 256],
  ['Hiragana', 512],
  ['Katakana', 1024],
  ['Hangul', 2048],
] as const

type Range = readonly [start: number, end: number, allowedScriptBitset: number]

function generateRanges(): readonly Range[] {
  if (
    process.versions.unicode !== EXPECTED_UNICODE_VERSION ||
    process.versions.icu !== EXPECTED_ICU_VERSION
  ) {
    throw new Error(
      `Unicode runtime mismatch: ${process.versions.unicode}/${process.versions.icu}`,
    )
  }
  const letterPattern = /^\p{Letter}$/u
  const scriptPatterns = SCRIPTS.map(
    ([script, bit]) =>
      [new RegExp(`^\\p{Script_Extensions=${script}}$`, 'u'), bit] as const,
  )
  const ranges: Range[] = []
  let activeStart = -1
  let activeEnd = -1
  let activeBits = -1

  for (let codePoint = 0; codePoint <= 0x10ffff; codePoint += 1) {
    if (codePoint >= 0xd800 && codePoint <= 0xdfff) continue
    const scalar = String.fromCodePoint(codePoint)
    if (!letterPattern.test(scalar)) continue
    let bits = 0
    for (const [pattern, bit] of scriptPatterns) {
      if (pattern.test(scalar)) bits |= bit
    }
    if (codePoint === activeEnd + 1 && bits === activeBits) {
      activeEnd = codePoint
      continue
    }
    if (activeStart >= 0) ranges.push([activeStart, activeEnd, activeBits])
    activeStart = codePoint
    activeEnd = codePoint
    activeBits = bits
  }
  if (activeStart >= 0) ranges.push([activeStart, activeEnd, activeBits])
  return Object.freeze(ranges)
}

function render(
  ranges: readonly Range[],
): Readonly<{ table: string; tableDigest: string }> {
  const canonicalRows = JSON.stringify(ranges)
  const tableDigest = createHash('sha256')
    .update('repkey-ai-language-script-extensions-v17\0', 'utf8')
    .update(canonicalRows, 'utf8')
    .digest('hex')
  const flatRows = ranges.flatMap(([start, end, bits]) => [start, end, bits])
  const rows = Array.from({ length: Math.ceil(flatRows.length / 12) }, (_, index) =>
    flatRows
      .slice(index * 12, index * 12 + 12)
      .map((value) => `0x${value.toString(16)}`)
      .join(', '),
  )
    .map((row) => `  ${row},`)
    .join('\n')
  return {
    tableDigest,
    table:
      `// Generated by scripts/generate-ai-language-script-table.ts. Do not edit.\n` +
      `export const AI_LANGUAGE_SCRIPT_UNICODE_VERSION = '${EXPECTED_UNICODE_VERSION}.0' as const\n` +
      `export const AI_LANGUAGE_SCRIPT_ICU_VERSION = '${EXPECTED_ICU_VERSION}' as const\n` +
      `export const AI_LANGUAGE_SCRIPT_TABLE_DIGEST = '${tableDigest}' as const\n` +
      `export const AI_LANGUAGE_SCRIPT_RANGE_COUNT = ${ranges.length} as const\n` +
      `export const AI_LANGUAGE_SCRIPT_RANGES = new Uint32Array([\n${rows}\n])\n`,
  }
}

const rendered = render(generateRanges())
const generated = await format(rendered.table, {
  ...PRETTIER_CONFIG,
  filepath: OUTPUT,
})
const sha256 = (value: string | Uint8Array) =>
  createHash('sha256').update(value).digest('hex')
const wrapperBytes = readFileSync(resolve(ROOT, WRAPPER_PATH))
const generatorBytes = readFileSync(resolve(ROOT, GENERATOR_PATH))
const vectors = JSON.parse(readFileSync(resolve(ROOT, VECTORS_PATH), 'utf8')) as unknown
const canonicalVectorBytes = Buffer.from(canonicalizeRfc8785(vectors), 'utf8')
const manifest = Object.freeze({
  version: 'language-script-consistency-v1',
  unicodeVersion: `${EXPECTED_UNICODE_VERSION}.0`,
  icuVersion: EXPECTED_ICU_VERSION,
  generatedTableDigest: rendered.tableDigest,
  thresholdNumerator: 4,
  thresholdDenominator: 5,
  scriptMasks: Object.freeze({
    Latn: 1,
    Cyrl: 2,
    Arab: 4,
    Hebr: 8,
    Deva: 16,
    Beng: 32,
    Taml: 64,
    Thai: 128,
    Hans: 256,
    Hant: 256,
    Jpan: 1792,
    Kore: 2304,
  }),
  generator: Object.freeze({ path: GENERATOR_PATH, sha256: sha256(generatorBytes) }),
  table: Object.freeze({ path: TABLE_PATH, sha256: sha256(generated) }),
  wrapper: Object.freeze({ path: WRAPPER_PATH, sha256: sha256(wrapperBytes) }),
  vectors: Object.freeze({ path: VECTORS_PATH, sha256: sha256(canonicalVectorBytes) }),
  attestationDigest: computeAiLanguageProfileDigest(
    'repkey-language-script-consistency-profile-v1\0',
    [
      { path: WRAPPER_PATH, bytes: wrapperBytes },
      { path: VECTORS_PATH, bytes: canonicalVectorBytes },
      { path: GENERATOR_PATH, bytes: generatorBytes },
      { path: TABLE_PATH, bytes: Buffer.from(generated, 'utf8') },
    ],
  ),
})
const generatedManifest = await format(JSON.stringify(manifest), {
  ...PRETTIER_CONFIG,
  filepath: MANIFEST_OUTPUT,
})
if (process.argv.includes('--check')) {
  if (readFileSync(OUTPUT, 'utf8') !== generated) {
    throw new Error('Generated language Script_Extensions table is stale')
  }
  if (readFileSync(MANIFEST_OUTPUT, 'utf8') !== generatedManifest) {
    throw new Error('Generated language Script_Extensions manifest is stale')
  }
  process.stdout.write('Language Script_Extensions table and manifest are current\n')
} else {
  mkdirSync(dirname(OUTPUT), { recursive: true })
  writeFileSync(OUTPUT, generated, 'utf8')
  writeFileSync(MANIFEST_OUTPUT, generatedManifest, 'utf8')
  process.stdout.write(`Generated ${OUTPUT} and ${MANIFEST_OUTPUT}\n`)
}
