import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import process from 'node:process'

const ROOT = resolve(import.meta.dirname, '..')
const INPUT = resolve(ROOT, 'vendor/unicode/17.0.0/CaseFolding.txt')
const OUTPUT = resolve(ROOT, 'src/shared/generated/ai-unicode-case-folding-v17.ts')
const EXPECTED_INPUT_SHA256 =
  '84a8df1d87b5fde9b480d95769e0817416e3708b17fb473e4f1eac18eb7a8653'

type Mapping = Readonly<{ codePoint: number; folded: string }>

function parseMappings(source: string): ReadonlyArray<Mapping> {
  if (source.startsWith('\uFEFF') || source.includes('\r')) {
    throw new Error('CaseFolding.txt must be UTF-8 without BOM and use LF line endings')
  }
  if (!source.startsWith('# CaseFolding-17.0.0.txt\n')) {
    throw new Error('Unexpected Unicode case-folding version')
  }

  const mappings: Mapping[] = []
  const seen = new Set<number>()
  for (const [lineIndex, rawLine] of source.split('\n').entries()) {
    const body = rawLine.split('#', 1)[0]?.trim()
    if (!body) continue
    const fields = body.split(';').map((field) => field.trim())
    if (fields.length !== 4 || fields[3] !== '') {
      throw new Error(`Malformed mapping at line ${lineIndex + 1}`)
    }
    const [codePointHex, status, mappingHex] = fields
    if (status !== 'C' && status !== 'F') continue
    if (!/^[0-9A-F]{4,6}$/.test(codePointHex ?? '')) {
      throw new Error(`Malformed code point at line ${lineIndex + 1}`)
    }
    const codePoint = Number.parseInt(codePointHex!, 16)
    if (seen.has(codePoint)) throw new Error(`Duplicate mapping for U+${codePointHex}`)
    const foldedCodePoints = (mappingHex ?? '').split(' ').map((value) => {
      if (!/^[0-9A-F]{4,6}$/.test(value)) {
        throw new Error(`Malformed folded scalar at line ${lineIndex + 1}`)
      }
      return Number.parseInt(value, 16)
    })
    const folded = String.fromCodePoint(...foldedCodePoints)
    if (folded.length === 0) throw new Error(`Empty mapping at line ${lineIndex + 1}`)
    seen.add(codePoint)
    mappings.push(Object.freeze({ codePoint, folded }))
  }
  mappings.sort((left, right) => left.codePoint - right.codePoint)
  return Object.freeze(mappings)
}

function render(mappings: ReadonlyArray<Mapping>, sourceSha256: string): string {
  const rows = mappings
    .map(
      ({ codePoint, folded }) =>
        `  [0x${codePoint.toString(16).toUpperCase()}, ${JSON.stringify(folded)}],`,
    )
    .join('\n')
  return (
    `// Generated by scripts/generate-ai-unicode-case-folding.ts. Do not edit.\n` +
    `export const AI_UNICODE_CASE_FOLDING_VERSION = '17.0.0' as const\n` +
    `export const AI_UNICODE_CASE_FOLDING_SOURCE_SHA256 = '${sourceSha256}' as const\n\n` +
    `export const AI_UNICODE_CASE_FOLDING_V17: ReadonlyArray<\n` +
    `  readonly [codePoint: number, folded: string]\n` +
    `> = Object.freeze([\n${rows}\n])\n`
  )
}

const inputBytes = readFileSync(INPUT)
const inputSha256 = createHash('sha256').update(inputBytes).digest('hex')
if (inputSha256 !== EXPECTED_INPUT_SHA256) {
  throw new Error(`CaseFolding.txt digest mismatch: ${inputSha256}`)
}
const generated = render(parseMappings(inputBytes.toString('utf8')), inputSha256)

if (process.argv.includes('--check')) {
  const current = readFileSync(OUTPUT, 'utf8')
  if (current !== generated) throw new Error('Generated Unicode case-fold table is stale')
  process.stdout.write('Unicode case-fold table is current\n')
} else {
  mkdirSync(dirname(OUTPUT), { recursive: true })
  writeFileSync(OUTPUT, generated, 'utf8')
  process.stdout.write(`Generated ${OUTPUT}\n`)
}
