/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiHealthIndexRouteImport } from './routes/api/health/index'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff/index'
import { Route as AuthenticatedPropertiesIndexRouteImport } from './routes/_authenticated/properties/index'
import { Route as PPropertySlugPortalSlugRouteImport } from './routes/p/$propertySlug/$portalSlug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedPropertiesNewRouteImport } from './routes/_authenticated/properties/new'
import { Route as AuthenticatedPropertiesPropertyIdRouteImport } from './routes/_authenticated/properties/$propertyId'
import { Route as AuthenticatedPropertiesPropertyIdIndexRouteImport } from './routes/_authenticated/properties/$propertyId/index'
import { Route as ApiPublicClickLinkIdRouteImport } from './routes/api/public/click/$linkId'
import { Route as ApiPortalsIdQrRouteImport } from './routes/api/portals/$id/qr'
import { Route as AuthenticatedPropertiesPropertyIdReviewsRouteImport } from './routes/_authenticated/properties/$propertyId/reviews'
import { Route as AuthenticatedPropertiesPropertyIdMetricsRouteImport } from './routes/_authenticated/properties/$propertyId/metrics'
import { Route as AuthenticatedPropertiesPropertyIdMembersRouteImport } from './routes/_authenticated/properties/$propertyId/members'
import { Route as AuthenticatedPropertiesPropertyIdTeamsIndexRouteImport } from './routes/_authenticated/properties/$propertyId/teams/index'
import { Route as AuthenticatedPropertiesPropertyIdStaffIndexRouteImport } from './routes/_authenticated/properties/$propertyId/staff/index'
import { Route as AuthenticatedPropertiesPropertyIdPortalsIndexRouteImport } from './routes/_authenticated/properties/$propertyId/portals/index'
import { Route as AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteImport } from './routes/_authenticated/properties/$propertyId/teams/$teamId'
import { Route as AuthenticatedPropertiesPropertyIdSettingsPropertyRouteImport } from './routes/_authenticated/properties/$propertyId/settings/property'
import { Route as AuthenticatedPropertiesPropertyIdSettingsOrganizationRouteImport } from './routes/_authenticated/properties/$propertyId/settings/organization'
import { Route as AuthenticatedPropertiesPropertyIdPortalsNewRouteImport } from './routes/_authenticated/properties/$propertyId/portals/new'
import { Route as AuthenticatedPropertiesPropertyIdPortalsPortalIdRouteImport } from './routes/_authenticated/properties/$propertyId/portals/$portalId'
import { Route as AuthenticatedPropertiesPropertyIdTeamsTeamIdIndexRouteImport } from './routes/_authenticated/properties/$propertyId/teams/$teamId/index'
import { Route as AuthenticatedPropertiesPropertyIdTeamsTeamIdMembersRouteImport } from './routes/_authenticated/properties/$propertyId/teams/$teamId/members'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiHealthIndexRoute = ApiHealthIndexRouteImport.update({
  id: '/api/health/',
  path: '/api/health/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPropertiesIndexRoute = AuthenticatedPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PPropertySlugPortalSlugRoute = PPropertySlugPortalSlugRouteImport.update({
  id: '/p/$propertySlug/$portalSlug',
  path: '/p/$propertySlug/$portalSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPropertiesNewRoute = AuthenticatedPropertiesNewRouteImport.update({
  id: '/properties/new',
  path: '/properties/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPropertiesPropertyIdRoute =
  AuthenticatedPropertiesPropertyIdRouteImport.update({
    id: '/properties/$propertyId',
    path: '/properties/$propertyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdIndexRoute =
  AuthenticatedPropertiesPropertyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const ApiPublicClickLinkIdRoute = ApiPublicClickLinkIdRouteImport.update({
  id: '/api/public/click/$linkId',
  path: '/api/public/click/$linkId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalsIdQrRoute = ApiPortalsIdQrRouteImport.update({
  id: '/api/portals/$id/qr',
  path: '/api/portals/$id/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPropertiesPropertyIdReviewsRoute =
  AuthenticatedPropertiesPropertyIdReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdMetricsRoute =
  AuthenticatedPropertiesPropertyIdMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdMembersRoute =
  AuthenticatedPropertiesPropertyIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdTeamsIndexRoute =
  AuthenticatedPropertiesPropertyIdTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdStaffIndexRoute =
  AuthenticatedPropertiesPropertyIdStaffIndexRouteImport.update({
    id: '/staff/',
    path: '/staff/',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdPortalsIndexRoute =
  AuthenticatedPropertiesPropertyIdPortalsIndexRouteImport.update({
    id: '/portals/',
    path: '/portals/',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdTeamsTeamIdRoute =
  AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteImport.update({
    id: '/teams/$teamId',
    path: '/teams/$teamId',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdSettingsPropertyRoute =
  AuthenticatedPropertiesPropertyIdSettingsPropertyRouteImport.update({
    id: '/settings/property',
    path: '/settings/property',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdSettingsOrganizationRoute =
  AuthenticatedPropertiesPropertyIdSettingsOrganizationRouteImport.update({
    id: '/settings/organization',
    path: '/settings/organization',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdPortalsNewRoute =
  AuthenticatedPropertiesPropertyIdPortalsNewRouteImport.update({
    id: '/portals/new',
    path: '/portals/new',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdPortalsPortalIdRoute =
  AuthenticatedPropertiesPropertyIdPortalsPortalIdRouteImport.update({
    id: '/portals/$portalId',
    path: '/portals/$portalId',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdTeamsTeamIdIndexRoute =
  AuthenticatedPropertiesPropertyIdTeamsTeamIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdTeamsTeamIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdTeamsTeamIdMembersRoute =
  AuthenticatedPropertiesPropertyIdTeamsTeamIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdTeamsTeamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRouteWithChildren
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/p/$propertySlug/$portalSlug': typeof PPropertySlugPortalSlugRoute
  '/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/api/health/': typeof ApiHealthIndexRoute
  '/properties/$propertyId/members': typeof AuthenticatedPropertiesPropertyIdMembersRoute
  '/properties/$propertyId/metrics': typeof AuthenticatedPropertiesPropertyIdMetricsRoute
  '/properties/$propertyId/reviews': typeof AuthenticatedPropertiesPropertyIdReviewsRoute
  '/api/portals/$id/qr': typeof ApiPortalsIdQrRoute
  '/api/public/click/$linkId': typeof ApiPublicClickLinkIdRoute
  '/properties/$propertyId/': typeof AuthenticatedPropertiesPropertyIdIndexRoute
  '/properties/$propertyId/portals/$portalId': typeof AuthenticatedPropertiesPropertyIdPortalsPortalIdRoute
  '/properties/$propertyId/portals/new': typeof AuthenticatedPropertiesPropertyIdPortalsNewRoute
  '/properties/$propertyId/settings/organization': typeof AuthenticatedPropertiesPropertyIdSettingsOrganizationRoute
  '/properties/$propertyId/settings/property': typeof AuthenticatedPropertiesPropertyIdSettingsPropertyRoute
  '/properties/$propertyId/teams/$teamId': typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteWithChildren
  '/properties/$propertyId/portals/': typeof AuthenticatedPropertiesPropertyIdPortalsIndexRoute
  '/properties/$propertyId/staff/': typeof AuthenticatedPropertiesPropertyIdStaffIndexRoute
  '/properties/$propertyId/teams/': typeof AuthenticatedPropertiesPropertyIdTeamsIndexRoute
  '/properties/$propertyId/teams/$teamId/members': typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdMembersRoute
  '/properties/$propertyId/teams/$teamId/': typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/p/$propertySlug/$portalSlug': typeof PPropertySlugPortalSlugRoute
  '/properties': typeof AuthenticatedPropertiesIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/api/health': typeof ApiHealthIndexRoute
  '/properties/$propertyId/members': typeof AuthenticatedPropertiesPropertyIdMembersRoute
  '/properties/$propertyId/metrics': typeof AuthenticatedPropertiesPropertyIdMetricsRoute
  '/properties/$propertyId/reviews': typeof AuthenticatedPropertiesPropertyIdReviewsRoute
  '/api/portals/$id/qr': typeof ApiPortalsIdQrRoute
  '/api/public/click/$linkId': typeof ApiPublicClickLinkIdRoute
  '/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdIndexRoute
  '/properties/$propertyId/portals/$portalId': typeof AuthenticatedPropertiesPropertyIdPortalsPortalIdRoute
  '/properties/$propertyId/portals/new': typeof AuthenticatedPropertiesPropertyIdPortalsNewRoute
  '/properties/$propertyId/settings/organization': typeof AuthenticatedPropertiesPropertyIdSettingsOrganizationRoute
  '/properties/$propertyId/settings/property': typeof AuthenticatedPropertiesPropertyIdSettingsPropertyRoute
  '/properties/$propertyId/portals': typeof AuthenticatedPropertiesPropertyIdPortalsIndexRoute
  '/properties/$propertyId/staff': typeof AuthenticatedPropertiesPropertyIdStaffIndexRoute
  '/properties/$propertyId/teams': typeof AuthenticatedPropertiesPropertyIdTeamsIndexRoute
  '/properties/$propertyId/teams/$teamId/members': typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdMembersRoute
  '/properties/$propertyId/teams/$teamId': typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRouteWithChildren
  '/_authenticated/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/p/$propertySlug/$portalSlug': typeof PPropertySlugPortalSlugRoute
  '/_authenticated/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/api/health/': typeof ApiHealthIndexRoute
  '/_authenticated/properties/$propertyId/members': typeof AuthenticatedPropertiesPropertyIdMembersRoute
  '/_authenticated/properties/$propertyId/metrics': typeof AuthenticatedPropertiesPropertyIdMetricsRoute
  '/_authenticated/properties/$propertyId/reviews': typeof AuthenticatedPropertiesPropertyIdReviewsRoute
  '/api/portals/$id/qr': typeof ApiPortalsIdQrRoute
  '/api/public/click/$linkId': typeof ApiPublicClickLinkIdRoute
  '/_authenticated/properties/$propertyId/': typeof AuthenticatedPropertiesPropertyIdIndexRoute
  '/_authenticated/properties/$propertyId/portals/$portalId': typeof AuthenticatedPropertiesPropertyIdPortalsPortalIdRoute
  '/_authenticated/properties/$propertyId/portals/new': typeof AuthenticatedPropertiesPropertyIdPortalsNewRoute
  '/_authenticated/properties/$propertyId/settings/organization': typeof AuthenticatedPropertiesPropertyIdSettingsOrganizationRoute
  '/_authenticated/properties/$propertyId/settings/property': typeof AuthenticatedPropertiesPropertyIdSettingsPropertyRoute
  '/_authenticated/properties/$propertyId/teams/$teamId': typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteWithChildren
  '/_authenticated/properties/$propertyId/portals/': typeof AuthenticatedPropertiesPropertyIdPortalsIndexRoute
  '/_authenticated/properties/$propertyId/staff/': typeof AuthenticatedPropertiesPropertyIdStaffIndexRoute
  '/_authenticated/properties/$propertyId/teams/': typeof AuthenticatedPropertiesPropertyIdTeamsIndexRoute
  '/_authenticated/properties/$propertyId/teams/$teamId/members': typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdMembersRoute
  '/_authenticated/properties/$propertyId/teams/$teamId/': typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/join'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/properties/$propertyId'
    | '/properties/new'
    | '/api/auth/$'
    | '/p/$propertySlug/$portalSlug'
    | '/properties/'
    | '/staff/'
    | '/api/health/'
    | '/properties/$propertyId/members'
    | '/properties/$propertyId/metrics'
    | '/properties/$propertyId/reviews'
    | '/api/portals/$id/qr'
    | '/api/public/click/$linkId'
    | '/properties/$propertyId/'
    | '/properties/$propertyId/portals/$portalId'
    | '/properties/$propertyId/portals/new'
    | '/properties/$propertyId/settings/organization'
    | '/properties/$propertyId/settings/property'
    | '/properties/$propertyId/teams/$teamId'
    | '/properties/$propertyId/portals/'
    | '/properties/$propertyId/staff/'
    | '/properties/$propertyId/teams/'
    | '/properties/$propertyId/teams/$teamId/members'
    | '/properties/$propertyId/teams/$teamId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/join'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/properties/new'
    | '/api/auth/$'
    | '/p/$propertySlug/$portalSlug'
    | '/properties'
    | '/staff'
    | '/api/health'
    | '/properties/$propertyId/members'
    | '/properties/$propertyId/metrics'
    | '/properties/$propertyId/reviews'
    | '/api/portals/$id/qr'
    | '/api/public/click/$linkId'
    | '/properties/$propertyId'
    | '/properties/$propertyId/portals/$portalId'
    | '/properties/$propertyId/portals/new'
    | '/properties/$propertyId/settings/organization'
    | '/properties/$propertyId/settings/property'
    | '/properties/$propertyId/portals'
    | '/properties/$propertyId/staff'
    | '/properties/$propertyId/teams'
    | '/properties/$propertyId/teams/$teamId/members'
    | '/properties/$propertyId/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invitation'
    | '/join'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/properties/$propertyId'
    | '/_authenticated/properties/new'
    | '/api/auth/$'
    | '/p/$propertySlug/$portalSlug'
    | '/_authenticated/properties/'
    | '/_authenticated/staff/'
    | '/api/health/'
    | '/_authenticated/properties/$propertyId/members'
    | '/_authenticated/properties/$propertyId/metrics'
    | '/_authenticated/properties/$propertyId/reviews'
    | '/api/portals/$id/qr'
    | '/api/public/click/$linkId'
    | '/_authenticated/properties/$propertyId/'
    | '/_authenticated/properties/$propertyId/portals/$portalId'
    | '/_authenticated/properties/$propertyId/portals/new'
    | '/_authenticated/properties/$propertyId/settings/organization'
    | '/_authenticated/properties/$propertyId/settings/property'
    | '/_authenticated/properties/$propertyId/teams/$teamId'
    | '/_authenticated/properties/$propertyId/portals/'
    | '/_authenticated/properties/$propertyId/staff/'
    | '/_authenticated/properties/$propertyId/teams/'
    | '/_authenticated/properties/$propertyId/teams/$teamId/members'
    | '/_authenticated/properties/$propertyId/teams/$teamId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  PPropertySlugPortalSlugRoute: typeof PPropertySlugPortalSlugRoute
  ApiHealthIndexRoute: typeof ApiHealthIndexRoute
  ApiPortalsIdQrRoute: typeof ApiPortalsIdQrRoute
  ApiPublicClickLinkIdRoute: typeof ApiPublicClickLinkIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/health/': {
      id: '/api/health/'
      path: '/api/health'
      fullPath: '/api/health/'
      preLoaderRoute: typeof ApiHealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties/': {
      id: '/_authenticated/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AuthenticatedPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/p/$propertySlug/$portalSlug': {
      id: '/p/$propertySlug/$portalSlug'
      path: '/p/$propertySlug/$portalSlug'
      fullPath: '/p/$propertySlug/$portalSlug'
      preLoaderRoute: typeof PPropertySlugPortalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/properties/new': {
      id: '/_authenticated/properties/new'
      path: '/properties/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof AuthenticatedPropertiesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties/$propertyId': {
      id: '/_authenticated/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties/$propertyId/': {
      id: '/_authenticated/properties/$propertyId/'
      path: '/'
      fullPath: '/properties/$propertyId/'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdIndexRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/api/public/click/$linkId': {
      id: '/api/public/click/$linkId'
      path: '/api/public/click/$linkId'
      fullPath: '/api/public/click/$linkId'
      preLoaderRoute: typeof ApiPublicClickLinkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portals/$id/qr': {
      id: '/api/portals/$id/qr'
      path: '/api/portals/$id/qr'
      fullPath: '/api/portals/$id/qr'
      preLoaderRoute: typeof ApiPortalsIdQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/properties/$propertyId/reviews': {
      id: '/_authenticated/properties/$propertyId/reviews'
      path: '/reviews'
      fullPath: '/properties/$propertyId/reviews'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdReviewsRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/_authenticated/properties/$propertyId/metrics': {
      id: '/_authenticated/properties/$propertyId/metrics'
      path: '/metrics'
      fullPath: '/properties/$propertyId/metrics'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdMetricsRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/_authenticated/properties/$propertyId/members': {
      id: '/_authenticated/properties/$propertyId/members'
      path: '/members'
      fullPath: '/properties/$propertyId/members'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdMembersRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/_authenticated/properties/$propertyId/teams/': {
      id: '/_authenticated/properties/$propertyId/teams/'
      path: '/teams'
      fullPath: '/properties/$propertyId/teams/'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/_authenticated/properties/$propertyId/staff/': {
      id: '/_authenticated/properties/$propertyId/staff/'
      path: '/staff'
      fullPath: '/properties/$propertyId/staff/'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdStaffIndexRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/_authenticated/properties/$propertyId/portals/': {
      id: '/_authenticated/properties/$propertyId/portals/'
      path: '/portals'
      fullPath: '/properties/$propertyId/portals/'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdPortalsIndexRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/_authenticated/properties/$propertyId/teams/$teamId': {
      id: '/_authenticated/properties/$propertyId/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/properties/$propertyId/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/_authenticated/properties/$propertyId/settings/property': {
      id: '/_authenticated/properties/$propertyId/settings/property'
      path: '/settings/property'
      fullPath: '/properties/$propertyId/settings/property'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdSettingsPropertyRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/_authenticated/properties/$propertyId/settings/organization': {
      id: '/_authenticated/properties/$propertyId/settings/organization'
      path: '/settings/organization'
      fullPath: '/properties/$propertyId/settings/organization'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdSettingsOrganizationRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/_authenticated/properties/$propertyId/portals/new': {
      id: '/_authenticated/properties/$propertyId/portals/new'
      path: '/portals/new'
      fullPath: '/properties/$propertyId/portals/new'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdPortalsNewRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/_authenticated/properties/$propertyId/portals/$portalId': {
      id: '/_authenticated/properties/$propertyId/portals/$portalId'
      path: '/portals/$portalId'
      fullPath: '/properties/$propertyId/portals/$portalId'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdPortalsPortalIdRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/_authenticated/properties/$propertyId/teams/$teamId/': {
      id: '/_authenticated/properties/$propertyId/teams/$teamId/'
      path: '/'
      fullPath: '/properties/$propertyId/teams/$teamId/'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdIndexRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdRoute
    }
    '/_authenticated/properties/$propertyId/teams/$teamId/members': {
      id: '/_authenticated/properties/$propertyId/teams/$teamId/members'
      path: '/members'
      fullPath: '/properties/$propertyId/teams/$teamId/members'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdMembersRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdRoute
    }
  }
}

interface AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteChildren {
  AuthenticatedPropertiesPropertyIdTeamsTeamIdMembersRoute: typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdMembersRoute
  AuthenticatedPropertiesPropertyIdTeamsTeamIdIndexRoute: typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdIndexRoute
}

const AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteChildren: AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteChildren =
  {
    AuthenticatedPropertiesPropertyIdTeamsTeamIdMembersRoute:
      AuthenticatedPropertiesPropertyIdTeamsTeamIdMembersRoute,
    AuthenticatedPropertiesPropertyIdTeamsTeamIdIndexRoute:
      AuthenticatedPropertiesPropertyIdTeamsTeamIdIndexRoute,
  }

const AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteWithChildren =
  AuthenticatedPropertiesPropertyIdTeamsTeamIdRoute._addFileChildren(
    AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteChildren,
  )

interface AuthenticatedPropertiesPropertyIdRouteChildren {
  AuthenticatedPropertiesPropertyIdMembersRoute: typeof AuthenticatedPropertiesPropertyIdMembersRoute
  AuthenticatedPropertiesPropertyIdMetricsRoute: typeof AuthenticatedPropertiesPropertyIdMetricsRoute
  AuthenticatedPropertiesPropertyIdReviewsRoute: typeof AuthenticatedPropertiesPropertyIdReviewsRoute
  AuthenticatedPropertiesPropertyIdIndexRoute: typeof AuthenticatedPropertiesPropertyIdIndexRoute
  AuthenticatedPropertiesPropertyIdPortalsPortalIdRoute: typeof AuthenticatedPropertiesPropertyIdPortalsPortalIdRoute
  AuthenticatedPropertiesPropertyIdPortalsNewRoute: typeof AuthenticatedPropertiesPropertyIdPortalsNewRoute
  AuthenticatedPropertiesPropertyIdSettingsOrganizationRoute: typeof AuthenticatedPropertiesPropertyIdSettingsOrganizationRoute
  AuthenticatedPropertiesPropertyIdSettingsPropertyRoute: typeof AuthenticatedPropertiesPropertyIdSettingsPropertyRoute
  AuthenticatedPropertiesPropertyIdTeamsTeamIdRoute: typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteWithChildren
  AuthenticatedPropertiesPropertyIdPortalsIndexRoute: typeof AuthenticatedPropertiesPropertyIdPortalsIndexRoute
  AuthenticatedPropertiesPropertyIdStaffIndexRoute: typeof AuthenticatedPropertiesPropertyIdStaffIndexRoute
  AuthenticatedPropertiesPropertyIdTeamsIndexRoute: typeof AuthenticatedPropertiesPropertyIdTeamsIndexRoute
}

const AuthenticatedPropertiesPropertyIdRouteChildren: AuthenticatedPropertiesPropertyIdRouteChildren =
  {
    AuthenticatedPropertiesPropertyIdMembersRoute:
      AuthenticatedPropertiesPropertyIdMembersRoute,
    AuthenticatedPropertiesPropertyIdMetricsRoute:
      AuthenticatedPropertiesPropertyIdMetricsRoute,
    AuthenticatedPropertiesPropertyIdReviewsRoute:
      AuthenticatedPropertiesPropertyIdReviewsRoute,
    AuthenticatedPropertiesPropertyIdIndexRoute:
      AuthenticatedPropertiesPropertyIdIndexRoute,
    AuthenticatedPropertiesPropertyIdPortalsPortalIdRoute:
      AuthenticatedPropertiesPropertyIdPortalsPortalIdRoute,
    AuthenticatedPropertiesPropertyIdPortalsNewRoute:
      AuthenticatedPropertiesPropertyIdPortalsNewRoute,
    AuthenticatedPropertiesPropertyIdSettingsOrganizationRoute:
      AuthenticatedPropertiesPropertyIdSettingsOrganizationRoute,
    AuthenticatedPropertiesPropertyIdSettingsPropertyRoute:
      AuthenticatedPropertiesPropertyIdSettingsPropertyRoute,
    AuthenticatedPropertiesPropertyIdTeamsTeamIdRoute:
      AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteWithChildren,
    AuthenticatedPropertiesPropertyIdPortalsIndexRoute:
      AuthenticatedPropertiesPropertyIdPortalsIndexRoute,
    AuthenticatedPropertiesPropertyIdStaffIndexRoute:
      AuthenticatedPropertiesPropertyIdStaffIndexRoute,
    AuthenticatedPropertiesPropertyIdTeamsIndexRoute:
      AuthenticatedPropertiesPropertyIdTeamsIndexRoute,
  }

const AuthenticatedPropertiesPropertyIdRouteWithChildren =
  AuthenticatedPropertiesPropertyIdRoute._addFileChildren(
    AuthenticatedPropertiesPropertyIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPropertiesPropertyIdRoute: typeof AuthenticatedPropertiesPropertyIdRouteWithChildren
  AuthenticatedPropertiesNewRoute: typeof AuthenticatedPropertiesNewRoute
  AuthenticatedPropertiesIndexRoute: typeof AuthenticatedPropertiesIndexRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPropertiesPropertyIdRoute:
    AuthenticatedPropertiesPropertyIdRouteWithChildren,
  AuthenticatedPropertiesNewRoute: AuthenticatedPropertiesNewRoute,
  AuthenticatedPropertiesIndexRoute: AuthenticatedPropertiesIndexRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  PPropertySlugPortalSlugRoute: PPropertySlugPortalSlugRoute,
  ApiHealthIndexRoute: ApiHealthIndexRoute,
  ApiPortalsIdQrRoute: ApiPortalsIdQrRoute,
  ApiPublicClickLinkIdRoute: ApiPublicClickLinkIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
