/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnavailableRouteImport } from './routes/unavailable'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiHealthIndexRouteImport } from './routes/api/health/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedPropertiesIndexRouteImport } from './routes/_authenticated/properties/index'
import { Route as AuthenticatedInboxIndexRouteImport } from './routes/_authenticated/inbox/index'
import { Route as AuthenticatedImportIndexRouteImport } from './routes/_authenticated/import/index'
import { Route as PPropertySlugPortalSlugRouteImport } from './routes/p/$propertySlug/$portalSlug'
import { Route as ApiHealthReadyRouteImport } from './routes/api/health/ready'
import { Route as ApiHealthMetricsRouteImport } from './routes/api/health/metrics'
import { Route as ApiHealthLiveRouteImport } from './routes/api/health/live'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings/security'
import { Route as AuthenticatedSettingsRecognitionRouteImport } from './routes/_authenticated/settings/recognition'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile'
import { Route as AuthenticatedSettingsPreferencesRouteImport } from './routes/_authenticated/settings/preferences'
import { Route as AuthenticatedSettingsOrganizationRouteImport } from './routes/_authenticated/settings/organization'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsMembersRouteImport } from './routes/_authenticated/settings/members'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings/integrations'
import { Route as AuthenticatedPropertiesPropertyIdRouteImport } from './routes/_authenticated/properties/$propertyId'
import { Route as AuthenticatedImportImportIdRouteImport } from './routes/_authenticated/import/$importId'
import { Route as AuthenticatedPropertiesPropertyIdIndexRouteImport } from './routes/_authenticated/properties/$propertyId/index'
import { Route as ApiWebhooksGbpNotificationsRouteImport } from './routes/api/webhooks/gbp/notifications'
import { Route as ApiPublicClickLinkIdRouteImport } from './routes/api/public/click/$linkId'
import { Route as ApiPortalsIdQrRouteImport } from './routes/api/portals/$id/qr'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google/callback'
import { Route as AuthenticatedPropertiesPropertyIdReviewsRouteImport } from './routes/_authenticated/properties/$propertyId/reviews'
import { Route as AuthenticatedPropertiesPropertyIdPeopleRouteImport } from './routes/_authenticated/properties/$propertyId/people'
import { Route as AuthenticatedPropertiesPropertyIdMetricsRouteImport } from './routes/_authenticated/properties/$propertyId/metrics'
import { Route as AuthenticatedPropertiesPropertyIdGoalsRouteImport } from './routes/_authenticated/properties/$propertyId/goals'
import { Route as AuthenticatedPropertiesPropertyIdPortalsIndexRouteImport } from './routes/_authenticated/properties/$propertyId/portals/index'
import { Route as AuthenticatedPropertiesPropertyIdGoalsIndexRouteImport } from './routes/_authenticated/properties/$propertyId/goals/index'
import { Route as AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteImport } from './routes/_authenticated/properties/$propertyId/teams/$teamId'
import { Route as AuthenticatedPropertiesPropertyIdPortalsNewRouteImport } from './routes/_authenticated/properties/$propertyId/portals/new'
import { Route as AuthenticatedPropertiesPropertyIdPortalsPortalIdRouteImport } from './routes/_authenticated/properties/$propertyId/portals/$portalId'
import { Route as AuthenticatedPropertiesPropertyIdGoalsNewRouteImport } from './routes/_authenticated/properties/$propertyId/goals/new'
import { Route as AuthenticatedPropertiesPropertyIdGoalsGoalIdRouteImport } from './routes/_authenticated/properties/$propertyId/goals/$goalId'
import { Route as AuthenticatedPropertiesPropertyIdTeamsTeamIdIndexRouteImport } from './routes/_authenticated/properties/$propertyId/teams/$teamId/index'
import { Route as AuthenticatedPropertiesPropertyIdTeamsTeamIdMembersRouteImport } from './routes/_authenticated/properties/$propertyId/teams/$teamId/members'

const UnavailableRoute = UnavailableRouteImport.update({
  id: '/unavailable',
  path: '/unavailable',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiHealthIndexRoute = ApiHealthIndexRouteImport.update({
  id: '/api/health/',
  path: '/api/health/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedPropertiesIndexRoute =
  AuthenticatedPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInboxIndexRoute = AuthenticatedInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImportIndexRoute =
  AuthenticatedImportIndexRouteImport.update({
    id: '/import/',
    path: '/import/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const PPropertySlugPortalSlugRoute = PPropertySlugPortalSlugRouteImport.update({
  id: '/p/$propertySlug/$portalSlug',
  path: '/p/$propertySlug/$portalSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthReadyRoute = ApiHealthReadyRouteImport.update({
  id: '/api/health/ready',
  path: '/api/health/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthMetricsRoute = ApiHealthMetricsRouteImport.update({
  id: '/api/health/metrics',
  path: '/api/health/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/api/health/live',
  path: '/api/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsRecognitionRoute =
  AuthenticatedSettingsRecognitionRouteImport.update({
    id: '/recognition',
    path: '/recognition',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPreferencesRoute =
  AuthenticatedSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsOrganizationRoute =
  AuthenticatedSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsMembersRoute =
  AuthenticatedSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdRoute =
  AuthenticatedPropertiesPropertyIdRouteImport.update({
    id: '/properties/$propertyId',
    path: '/properties/$propertyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportImportIdRoute =
  AuthenticatedImportImportIdRouteImport.update({
    id: '/import/$importId',
    path: '/import/$importId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdIndexRoute =
  AuthenticatedPropertiesPropertyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const ApiWebhooksGbpNotificationsRoute =
  ApiWebhooksGbpNotificationsRouteImport.update({
    id: '/api/webhooks/gbp/notifications',
    path: '/api/webhooks/gbp/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicClickLinkIdRoute = ApiPublicClickLinkIdRouteImport.update({
  id: '/api/public/click/$linkId',
  path: '/api/public/click/$linkId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalsIdQrRoute = ApiPortalsIdQrRouteImport.update({
  id: '/api/portals/$id/qr',
  path: '/api/portals/$id/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/api/auth/google/callback',
  path: '/api/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPropertiesPropertyIdReviewsRoute =
  AuthenticatedPropertiesPropertyIdReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdPeopleRoute =
  AuthenticatedPropertiesPropertyIdPeopleRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdMetricsRoute =
  AuthenticatedPropertiesPropertyIdMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdGoalsRoute =
  AuthenticatedPropertiesPropertyIdGoalsRouteImport.update({
    id: '/goals',
    path: '/goals',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdPortalsIndexRoute =
  AuthenticatedPropertiesPropertyIdPortalsIndexRouteImport.update({
    id: '/portals/',
    path: '/portals/',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdGoalsIndexRoute =
  AuthenticatedPropertiesPropertyIdGoalsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdGoalsRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdTeamsTeamIdRoute =
  AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteImport.update({
    id: '/teams/$teamId',
    path: '/teams/$teamId',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdPortalsNewRoute =
  AuthenticatedPropertiesPropertyIdPortalsNewRouteImport.update({
    id: '/portals/new',
    path: '/portals/new',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdPortalsPortalIdRoute =
  AuthenticatedPropertiesPropertyIdPortalsPortalIdRouteImport.update({
    id: '/portals/$portalId',
    path: '/portals/$portalId',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdGoalsNewRoute =
  AuthenticatedPropertiesPropertyIdGoalsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdGoalsRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdGoalsGoalIdRoute =
  AuthenticatedPropertiesPropertyIdGoalsGoalIdRouteImport.update({
    id: '/$goalId',
    path: '/$goalId',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdGoalsRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdTeamsTeamIdIndexRoute =
  AuthenticatedPropertiesPropertyIdTeamsTeamIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdTeamsTeamIdRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdTeamsTeamIdMembersRoute =
  AuthenticatedPropertiesPropertyIdTeamsTeamIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedPropertiesPropertyIdTeamsTeamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unavailable': typeof UnavailableRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/home': typeof AuthenticatedHomeRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/import/$importId': typeof AuthenticatedImportImportIdRoute
  '/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRouteWithChildren
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/recognition': typeof AuthenticatedSettingsRecognitionRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/metrics': typeof ApiHealthMetricsRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/p/$propertySlug/$portalSlug': typeof PPropertySlugPortalSlugRoute
  '/import/': typeof AuthenticatedImportIndexRoute
  '/inbox/': typeof AuthenticatedInboxIndexRoute
  '/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/health/': typeof ApiHealthIndexRoute
  '/properties/$propertyId/goals': typeof AuthenticatedPropertiesPropertyIdGoalsRouteWithChildren
  '/properties/$propertyId/metrics': typeof AuthenticatedPropertiesPropertyIdMetricsRoute
  '/properties/$propertyId/people': typeof AuthenticatedPropertiesPropertyIdPeopleRoute
  '/properties/$propertyId/reviews': typeof AuthenticatedPropertiesPropertyIdReviewsRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/portals/$id/qr': typeof ApiPortalsIdQrRoute
  '/api/public/click/$linkId': typeof ApiPublicClickLinkIdRoute
  '/api/webhooks/gbp/notifications': typeof ApiWebhooksGbpNotificationsRoute
  '/properties/$propertyId/': typeof AuthenticatedPropertiesPropertyIdIndexRoute
  '/properties/$propertyId/goals/$goalId': typeof AuthenticatedPropertiesPropertyIdGoalsGoalIdRoute
  '/properties/$propertyId/goals/new': typeof AuthenticatedPropertiesPropertyIdGoalsNewRoute
  '/properties/$propertyId/portals/$portalId': typeof AuthenticatedPropertiesPropertyIdPortalsPortalIdRoute
  '/properties/$propertyId/portals/new': typeof AuthenticatedPropertiesPropertyIdPortalsNewRoute
  '/properties/$propertyId/teams/$teamId': typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteWithChildren
  '/properties/$propertyId/goals/': typeof AuthenticatedPropertiesPropertyIdGoalsIndexRoute
  '/properties/$propertyId/portals/': typeof AuthenticatedPropertiesPropertyIdPortalsIndexRoute
  '/properties/$propertyId/teams/$teamId/members': typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdMembersRoute
  '/properties/$propertyId/teams/$teamId/': typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unavailable': typeof UnavailableRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/home': typeof AuthenticatedHomeRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/team': typeof AuthenticatedTeamRoute
  '/import/$importId': typeof AuthenticatedImportImportIdRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/recognition': typeof AuthenticatedSettingsRecognitionRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/metrics': typeof ApiHealthMetricsRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/p/$propertySlug/$portalSlug': typeof PPropertySlugPortalSlugRoute
  '/import': typeof AuthenticatedImportIndexRoute
  '/inbox': typeof AuthenticatedInboxIndexRoute
  '/properties': typeof AuthenticatedPropertiesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/api/health': typeof ApiHealthIndexRoute
  '/properties/$propertyId/metrics': typeof AuthenticatedPropertiesPropertyIdMetricsRoute
  '/properties/$propertyId/people': typeof AuthenticatedPropertiesPropertyIdPeopleRoute
  '/properties/$propertyId/reviews': typeof AuthenticatedPropertiesPropertyIdReviewsRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/portals/$id/qr': typeof ApiPortalsIdQrRoute
  '/api/public/click/$linkId': typeof ApiPublicClickLinkIdRoute
  '/api/webhooks/gbp/notifications': typeof ApiWebhooksGbpNotificationsRoute
  '/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdIndexRoute
  '/properties/$propertyId/goals/$goalId': typeof AuthenticatedPropertiesPropertyIdGoalsGoalIdRoute
  '/properties/$propertyId/goals/new': typeof AuthenticatedPropertiesPropertyIdGoalsNewRoute
  '/properties/$propertyId/portals/$portalId': typeof AuthenticatedPropertiesPropertyIdPortalsPortalIdRoute
  '/properties/$propertyId/portals/new': typeof AuthenticatedPropertiesPropertyIdPortalsNewRoute
  '/properties/$propertyId/goals': typeof AuthenticatedPropertiesPropertyIdGoalsIndexRoute
  '/properties/$propertyId/portals': typeof AuthenticatedPropertiesPropertyIdPortalsIndexRoute
  '/properties/$propertyId/teams/$teamId/members': typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdMembersRoute
  '/properties/$propertyId/teams/$teamId': typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unavailable': typeof UnavailableRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/import/$importId': typeof AuthenticatedImportImportIdRoute
  '/_authenticated/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRouteWithChildren
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/_authenticated/settings/members': typeof AuthenticatedSettingsMembersRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/_authenticated/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/recognition': typeof AuthenticatedSettingsRecognitionRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/metrics': typeof ApiHealthMetricsRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/p/$propertySlug/$portalSlug': typeof PPropertySlugPortalSlugRoute
  '/_authenticated/import/': typeof AuthenticatedImportIndexRoute
  '/_authenticated/inbox/': typeof AuthenticatedInboxIndexRoute
  '/_authenticated/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/api/health/': typeof ApiHealthIndexRoute
  '/_authenticated/properties/$propertyId/goals': typeof AuthenticatedPropertiesPropertyIdGoalsRouteWithChildren
  '/_authenticated/properties/$propertyId/metrics': typeof AuthenticatedPropertiesPropertyIdMetricsRoute
  '/_authenticated/properties/$propertyId/people': typeof AuthenticatedPropertiesPropertyIdPeopleRoute
  '/_authenticated/properties/$propertyId/reviews': typeof AuthenticatedPropertiesPropertyIdReviewsRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/portals/$id/qr': typeof ApiPortalsIdQrRoute
  '/api/public/click/$linkId': typeof ApiPublicClickLinkIdRoute
  '/api/webhooks/gbp/notifications': typeof ApiWebhooksGbpNotificationsRoute
  '/_authenticated/properties/$propertyId/': typeof AuthenticatedPropertiesPropertyIdIndexRoute
  '/_authenticated/properties/$propertyId/goals/$goalId': typeof AuthenticatedPropertiesPropertyIdGoalsGoalIdRoute
  '/_authenticated/properties/$propertyId/goals/new': typeof AuthenticatedPropertiesPropertyIdGoalsNewRoute
  '/_authenticated/properties/$propertyId/portals/$portalId': typeof AuthenticatedPropertiesPropertyIdPortalsPortalIdRoute
  '/_authenticated/properties/$propertyId/portals/new': typeof AuthenticatedPropertiesPropertyIdPortalsNewRoute
  '/_authenticated/properties/$propertyId/teams/$teamId': typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteWithChildren
  '/_authenticated/properties/$propertyId/goals/': typeof AuthenticatedPropertiesPropertyIdGoalsIndexRoute
  '/_authenticated/properties/$propertyId/portals/': typeof AuthenticatedPropertiesPropertyIdPortalsIndexRoute
  '/_authenticated/properties/$propertyId/teams/$teamId/members': typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdMembersRoute
  '/_authenticated/properties/$propertyId/teams/$teamId/': typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/join'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/unavailable'
    | '/dashboard'
    | '/home'
    | '/leaderboard'
    | '/progress'
    | '/settings'
    | '/team'
    | '/import/$importId'
    | '/properties/$propertyId'
    | '/settings/integrations'
    | '/settings/members'
    | '/settings/notifications'
    | '/settings/organization'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/recognition'
    | '/settings/security'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/metrics'
    | '/api/health/ready'
    | '/p/$propertySlug/$portalSlug'
    | '/import/'
    | '/inbox/'
    | '/properties/'
    | '/settings/'
    | '/api/health/'
    | '/properties/$propertyId/goals'
    | '/properties/$propertyId/metrics'
    | '/properties/$propertyId/people'
    | '/properties/$propertyId/reviews'
    | '/api/auth/google/callback'
    | '/api/portals/$id/qr'
    | '/api/public/click/$linkId'
    | '/api/webhooks/gbp/notifications'
    | '/properties/$propertyId/'
    | '/properties/$propertyId/goals/$goalId'
    | '/properties/$propertyId/goals/new'
    | '/properties/$propertyId/portals/$portalId'
    | '/properties/$propertyId/portals/new'
    | '/properties/$propertyId/teams/$teamId'
    | '/properties/$propertyId/goals/'
    | '/properties/$propertyId/portals/'
    | '/properties/$propertyId/teams/$teamId/members'
    | '/properties/$propertyId/teams/$teamId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/join'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/unavailable'
    | '/dashboard'
    | '/home'
    | '/leaderboard'
    | '/progress'
    | '/team'
    | '/import/$importId'
    | '/settings/integrations'
    | '/settings/members'
    | '/settings/notifications'
    | '/settings/organization'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/recognition'
    | '/settings/security'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/metrics'
    | '/api/health/ready'
    | '/p/$propertySlug/$portalSlug'
    | '/import'
    | '/inbox'
    | '/properties'
    | '/settings'
    | '/api/health'
    | '/properties/$propertyId/metrics'
    | '/properties/$propertyId/people'
    | '/properties/$propertyId/reviews'
    | '/api/auth/google/callback'
    | '/api/portals/$id/qr'
    | '/api/public/click/$linkId'
    | '/api/webhooks/gbp/notifications'
    | '/properties/$propertyId'
    | '/properties/$propertyId/goals/$goalId'
    | '/properties/$propertyId/goals/new'
    | '/properties/$propertyId/portals/$portalId'
    | '/properties/$propertyId/portals/new'
    | '/properties/$propertyId/goals'
    | '/properties/$propertyId/portals'
    | '/properties/$propertyId/teams/$teamId/members'
    | '/properties/$propertyId/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invitation'
    | '/join'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/unavailable'
    | '/_authenticated/dashboard'
    | '/_authenticated/home'
    | '/_authenticated/leaderboard'
    | '/_authenticated/progress'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/import/$importId'
    | '/_authenticated/properties/$propertyId'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/settings/members'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/organization'
    | '/_authenticated/settings/preferences'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/recognition'
    | '/_authenticated/settings/security'
    | '/api/auth/$'
    | '/api/health/live'
    | '/api/health/metrics'
    | '/api/health/ready'
    | '/p/$propertySlug/$portalSlug'
    | '/_authenticated/import/'
    | '/_authenticated/inbox/'
    | '/_authenticated/properties/'
    | '/_authenticated/settings/'
    | '/api/health/'
    | '/_authenticated/properties/$propertyId/goals'
    | '/_authenticated/properties/$propertyId/metrics'
    | '/_authenticated/properties/$propertyId/people'
    | '/_authenticated/properties/$propertyId/reviews'
    | '/api/auth/google/callback'
    | '/api/portals/$id/qr'
    | '/api/public/click/$linkId'
    | '/api/webhooks/gbp/notifications'
    | '/_authenticated/properties/$propertyId/'
    | '/_authenticated/properties/$propertyId/goals/$goalId'
    | '/_authenticated/properties/$propertyId/goals/new'
    | '/_authenticated/properties/$propertyId/portals/$portalId'
    | '/_authenticated/properties/$propertyId/portals/new'
    | '/_authenticated/properties/$propertyId/teams/$teamId'
    | '/_authenticated/properties/$propertyId/goals/'
    | '/_authenticated/properties/$propertyId/portals/'
    | '/_authenticated/properties/$propertyId/teams/$teamId/members'
    | '/_authenticated/properties/$propertyId/teams/$teamId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnavailableRoute: typeof UnavailableRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
  ApiHealthMetricsRoute: typeof ApiHealthMetricsRoute
  ApiHealthReadyRoute: typeof ApiHealthReadyRoute
  PPropertySlugPortalSlugRoute: typeof PPropertySlugPortalSlugRoute
  ApiHealthIndexRoute: typeof ApiHealthIndexRoute
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
  ApiPortalsIdQrRoute: typeof ApiPortalsIdQrRoute
  ApiPublicClickLinkIdRoute: typeof ApiPublicClickLinkIdRoute
  ApiWebhooksGbpNotificationsRoute: typeof ApiWebhooksGbpNotificationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unavailable': {
      id: '/unavailable'
      path: '/unavailable'
      fullPath: '/unavailable'
      preLoaderRoute: typeof UnavailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/health/': {
      id: '/api/health/'
      path: '/api/health'
      fullPath: '/api/health/'
      preLoaderRoute: typeof ApiHealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/properties/': {
      id: '/_authenticated/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AuthenticatedPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox/': {
      id: '/_authenticated/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AuthenticatedInboxIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import/': {
      id: '/_authenticated/import/'
      path: '/import'
      fullPath: '/import/'
      preLoaderRoute: typeof AuthenticatedImportIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/p/$propertySlug/$portalSlug': {
      id: '/p/$propertySlug/$portalSlug'
      path: '/p/$propertySlug/$portalSlug'
      fullPath: '/p/$propertySlug/$portalSlug'
      preLoaderRoute: typeof PPropertySlugPortalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/ready': {
      id: '/api/health/ready'
      path: '/api/health/ready'
      fullPath: '/api/health/ready'
      preLoaderRoute: typeof ApiHealthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/metrics': {
      id: '/api/health/metrics'
      path: '/api/health/metrics'
      fullPath: '/api/health/metrics'
      preLoaderRoute: typeof ApiHealthMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/live': {
      id: '/api/health/live'
      path: '/api/health/live'
      fullPath: '/api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/recognition': {
      id: '/_authenticated/settings/recognition'
      path: '/recognition'
      fullPath: '/settings/recognition'
      preLoaderRoute: typeof AuthenticatedSettingsRecognitionRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/preferences': {
      id: '/_authenticated/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AuthenticatedSettingsPreferencesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/organization': {
      id: '/_authenticated/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/members': {
      id: '/_authenticated/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AuthenticatedSettingsMembersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/properties/$propertyId': {
      id: '/_authenticated/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import/$importId': {
      id: '/_authenticated/import/$importId'
      path: '/import/$importId'
      fullPath: '/import/$importId'
      preLoaderRoute: typeof AuthenticatedImportImportIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties/$propertyId/': {
      id: '/_authenticated/properties/$propertyId/'
      path: '/'
      fullPath: '/properties/$propertyId/'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdIndexRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/api/webhooks/gbp/notifications': {
      id: '/api/webhooks/gbp/notifications'
      path: '/api/webhooks/gbp/notifications'
      fullPath: '/api/webhooks/gbp/notifications'
      preLoaderRoute: typeof ApiWebhooksGbpNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/click/$linkId': {
      id: '/api/public/click/$linkId'
      path: '/api/public/click/$linkId'
      fullPath: '/api/public/click/$linkId'
      preLoaderRoute: typeof ApiPublicClickLinkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portals/$id/qr': {
      id: '/api/portals/$id/qr'
      path: '/api/portals/$id/qr'
      fullPath: '/api/portals/$id/qr'
      preLoaderRoute: typeof ApiPortalsIdQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/api/auth/google/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/properties/$propertyId/reviews': {
      id: '/_authenticated/properties/$propertyId/reviews'
      path: '/reviews'
      fullPath: '/properties/$propertyId/reviews'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdReviewsRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/_authenticated/properties/$propertyId/people': {
      id: '/_authenticated/properties/$propertyId/people'
      path: '/people'
      fullPath: '/properties/$propertyId/people'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdPeopleRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/_authenticated/properties/$propertyId/metrics': {
      id: '/_authenticated/properties/$propertyId/metrics'
      path: '/metrics'
      fullPath: '/properties/$propertyId/metrics'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdMetricsRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/_authenticated/properties/$propertyId/goals': {
      id: '/_authenticated/properties/$propertyId/goals'
      path: '/goals'
      fullPath: '/properties/$propertyId/goals'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdGoalsRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/_authenticated/properties/$propertyId/portals/': {
      id: '/_authenticated/properties/$propertyId/portals/'
      path: '/portals'
      fullPath: '/properties/$propertyId/portals/'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdPortalsIndexRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/_authenticated/properties/$propertyId/goals/': {
      id: '/_authenticated/properties/$propertyId/goals/'
      path: '/'
      fullPath: '/properties/$propertyId/goals/'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdGoalsIndexRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdGoalsRoute
    }
    '/_authenticated/properties/$propertyId/teams/$teamId': {
      id: '/_authenticated/properties/$propertyId/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/properties/$propertyId/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/_authenticated/properties/$propertyId/portals/new': {
      id: '/_authenticated/properties/$propertyId/portals/new'
      path: '/portals/new'
      fullPath: '/properties/$propertyId/portals/new'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdPortalsNewRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/_authenticated/properties/$propertyId/portals/$portalId': {
      id: '/_authenticated/properties/$propertyId/portals/$portalId'
      path: '/portals/$portalId'
      fullPath: '/properties/$propertyId/portals/$portalId'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdPortalsPortalIdRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdRoute
    }
    '/_authenticated/properties/$propertyId/goals/new': {
      id: '/_authenticated/properties/$propertyId/goals/new'
      path: '/new'
      fullPath: '/properties/$propertyId/goals/new'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdGoalsNewRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdGoalsRoute
    }
    '/_authenticated/properties/$propertyId/goals/$goalId': {
      id: '/_authenticated/properties/$propertyId/goals/$goalId'
      path: '/$goalId'
      fullPath: '/properties/$propertyId/goals/$goalId'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdGoalsGoalIdRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdGoalsRoute
    }
    '/_authenticated/properties/$propertyId/teams/$teamId/': {
      id: '/_authenticated/properties/$propertyId/teams/$teamId/'
      path: '/'
      fullPath: '/properties/$propertyId/teams/$teamId/'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdIndexRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdRoute
    }
    '/_authenticated/properties/$propertyId/teams/$teamId/members': {
      id: '/_authenticated/properties/$propertyId/teams/$teamId/members'
      path: '/members'
      fullPath: '/properties/$propertyId/teams/$teamId/members'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdMembersRouteImport
      parentRoute: typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
  AuthenticatedSettingsMembersRoute: typeof AuthenticatedSettingsMembersRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsOrganizationRoute: typeof AuthenticatedSettingsOrganizationRoute
  AuthenticatedSettingsPreferencesRoute: typeof AuthenticatedSettingsPreferencesRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsRecognitionRoute: typeof AuthenticatedSettingsRecognitionRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
  AuthenticatedSettingsMembersRoute: AuthenticatedSettingsMembersRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsOrganizationRoute:
    AuthenticatedSettingsOrganizationRoute,
  AuthenticatedSettingsPreferencesRoute: AuthenticatedSettingsPreferencesRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsRecognitionRoute: AuthenticatedSettingsRecognitionRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedPropertiesPropertyIdGoalsRouteChildren {
  AuthenticatedPropertiesPropertyIdGoalsGoalIdRoute: typeof AuthenticatedPropertiesPropertyIdGoalsGoalIdRoute
  AuthenticatedPropertiesPropertyIdGoalsNewRoute: typeof AuthenticatedPropertiesPropertyIdGoalsNewRoute
  AuthenticatedPropertiesPropertyIdGoalsIndexRoute: typeof AuthenticatedPropertiesPropertyIdGoalsIndexRoute
}

const AuthenticatedPropertiesPropertyIdGoalsRouteChildren: AuthenticatedPropertiesPropertyIdGoalsRouteChildren =
  {
    AuthenticatedPropertiesPropertyIdGoalsGoalIdRoute:
      AuthenticatedPropertiesPropertyIdGoalsGoalIdRoute,
    AuthenticatedPropertiesPropertyIdGoalsNewRoute:
      AuthenticatedPropertiesPropertyIdGoalsNewRoute,
    AuthenticatedPropertiesPropertyIdGoalsIndexRoute:
      AuthenticatedPropertiesPropertyIdGoalsIndexRoute,
  }

const AuthenticatedPropertiesPropertyIdGoalsRouteWithChildren =
  AuthenticatedPropertiesPropertyIdGoalsRoute._addFileChildren(
    AuthenticatedPropertiesPropertyIdGoalsRouteChildren,
  )

interface AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteChildren {
  AuthenticatedPropertiesPropertyIdTeamsTeamIdMembersRoute: typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdMembersRoute
  AuthenticatedPropertiesPropertyIdTeamsTeamIdIndexRoute: typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdIndexRoute
}

const AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteChildren: AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteChildren =
  {
    AuthenticatedPropertiesPropertyIdTeamsTeamIdMembersRoute:
      AuthenticatedPropertiesPropertyIdTeamsTeamIdMembersRoute,
    AuthenticatedPropertiesPropertyIdTeamsTeamIdIndexRoute:
      AuthenticatedPropertiesPropertyIdTeamsTeamIdIndexRoute,
  }

const AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteWithChildren =
  AuthenticatedPropertiesPropertyIdTeamsTeamIdRoute._addFileChildren(
    AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteChildren,
  )

interface AuthenticatedPropertiesPropertyIdRouteChildren {
  AuthenticatedPropertiesPropertyIdGoalsRoute: typeof AuthenticatedPropertiesPropertyIdGoalsRouteWithChildren
  AuthenticatedPropertiesPropertyIdMetricsRoute: typeof AuthenticatedPropertiesPropertyIdMetricsRoute
  AuthenticatedPropertiesPropertyIdPeopleRoute: typeof AuthenticatedPropertiesPropertyIdPeopleRoute
  AuthenticatedPropertiesPropertyIdReviewsRoute: typeof AuthenticatedPropertiesPropertyIdReviewsRoute
  AuthenticatedPropertiesPropertyIdIndexRoute: typeof AuthenticatedPropertiesPropertyIdIndexRoute
  AuthenticatedPropertiesPropertyIdPortalsPortalIdRoute: typeof AuthenticatedPropertiesPropertyIdPortalsPortalIdRoute
  AuthenticatedPropertiesPropertyIdPortalsNewRoute: typeof AuthenticatedPropertiesPropertyIdPortalsNewRoute
  AuthenticatedPropertiesPropertyIdTeamsTeamIdRoute: typeof AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteWithChildren
  AuthenticatedPropertiesPropertyIdPortalsIndexRoute: typeof AuthenticatedPropertiesPropertyIdPortalsIndexRoute
}

const AuthenticatedPropertiesPropertyIdRouteChildren: AuthenticatedPropertiesPropertyIdRouteChildren =
  {
    AuthenticatedPropertiesPropertyIdGoalsRoute:
      AuthenticatedPropertiesPropertyIdGoalsRouteWithChildren,
    AuthenticatedPropertiesPropertyIdMetricsRoute:
      AuthenticatedPropertiesPropertyIdMetricsRoute,
    AuthenticatedPropertiesPropertyIdPeopleRoute:
      AuthenticatedPropertiesPropertyIdPeopleRoute,
    AuthenticatedPropertiesPropertyIdReviewsRoute:
      AuthenticatedPropertiesPropertyIdReviewsRoute,
    AuthenticatedPropertiesPropertyIdIndexRoute:
      AuthenticatedPropertiesPropertyIdIndexRoute,
    AuthenticatedPropertiesPropertyIdPortalsPortalIdRoute:
      AuthenticatedPropertiesPropertyIdPortalsPortalIdRoute,
    AuthenticatedPropertiesPropertyIdPortalsNewRoute:
      AuthenticatedPropertiesPropertyIdPortalsNewRoute,
    AuthenticatedPropertiesPropertyIdTeamsTeamIdRoute:
      AuthenticatedPropertiesPropertyIdTeamsTeamIdRouteWithChildren,
    AuthenticatedPropertiesPropertyIdPortalsIndexRoute:
      AuthenticatedPropertiesPropertyIdPortalsIndexRoute,
  }

const AuthenticatedPropertiesPropertyIdRouteWithChildren =
  AuthenticatedPropertiesPropertyIdRoute._addFileChildren(
    AuthenticatedPropertiesPropertyIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedImportImportIdRoute: typeof AuthenticatedImportImportIdRoute
  AuthenticatedPropertiesPropertyIdRoute: typeof AuthenticatedPropertiesPropertyIdRouteWithChildren
  AuthenticatedImportIndexRoute: typeof AuthenticatedImportIndexRoute
  AuthenticatedInboxIndexRoute: typeof AuthenticatedInboxIndexRoute
  AuthenticatedPropertiesIndexRoute: typeof AuthenticatedPropertiesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedImportImportIdRoute: AuthenticatedImportImportIdRoute,
  AuthenticatedPropertiesPropertyIdRoute:
    AuthenticatedPropertiesPropertyIdRouteWithChildren,
  AuthenticatedImportIndexRoute: AuthenticatedImportIndexRoute,
  AuthenticatedInboxIndexRoute: AuthenticatedInboxIndexRoute,
  AuthenticatedPropertiesIndexRoute: AuthenticatedPropertiesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnavailableRoute: UnavailableRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiHealthLiveRoute: ApiHealthLiveRoute,
  ApiHealthMetricsRoute: ApiHealthMetricsRoute,
  ApiHealthReadyRoute: ApiHealthReadyRoute,
  PPropertySlugPortalSlugRoute: PPropertySlugPortalSlugRoute,
  ApiHealthIndexRoute: ApiHealthIndexRoute,
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
  ApiPortalsIdQrRoute: ApiPortalsIdQrRoute,
  ApiPublicClickLinkIdRoute: ApiPublicClickLinkIdRoute,
  ApiWebhooksGbpNotificationsRoute: ApiWebhooksGbpNotificationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
